.size-snapshot.json, readme.md, src/index.ts
Made a mistake and forgot to update the dependencies ref. Also added documentation on performance and how Zustand calls selectors.
Edit - Removed the need for dependencies ref.
=>  Fix deps ref and add documentation

.size-snapshot.json, src/index.ts
=> Fix RefError when calling subscribe in middleware

readme.md
Because of this issue #119  I'm opening this PR to prevent others to go through the same problem I did
=> feat(readme): include ie compatibility information

.size-snapshot.json, src/index.ts, tests/test.tsx
=> Add replace flag in set

.size-snapshot.json, package.json, src/index.ts, src/shallow.ts, src/vanilla.ts, tests/test.tsx, tsconfig.json, yarn.lock
- update dev dependencies
- follow the changes in the updated packages
- run tsc for tests file with strict mode
=> [v3] update dev dependencies

.size-snapshot.json, src/index.ts
You can create hook from vanilla store.
=> [v3] create from store

.size-snapshot.json, package.json, readme.md, rollup.config.js, src/index.ts, src/shallow.ts, src/vanilla.ts, tests/test.tsx, tsconfig.json, yarn.lock
close #71 
close #118 
close #111
=> v3: unified api, vanilla store, and code clean up for v4

readme.md
Changed some minor stuff as I was going through the README
=> Minor README changes

readme.md
Just completes some code blocks for easier copy + pasting.
=> README update: complete code blocks

readme.md
=> Update readme.md example

example/src/resources/code.js
Small fix for the example code.
=> Fixing example code

src/middleware.ts
=> make the commit button work in the devtools

examples/src/App.js, examples/src/styles.css
Regarding #203
Maybe i went a bit too far - but it looks pretty responsive to me now, and the bear is fully visible on mobile, with some inbetween states as well.
Btw, was the preformatting for the code example deactivated on purpose?
=> [examples] enhance responsiveness and code readability

.size-snapshot.json, package.json, rollup.config.js, tsconfig.json, yarn.lock
See https://github.com/pmndrs/jotai/pull/154 for additional information about these changes.
=> Migrate to @rollup/* packages and make resolve plugin first to run

src/middleware.ts
close #216 
It uses CustomSetState.
(Note, if we'd support #212, it'd require total overhaul.)
=> improve middleware/combine types

src/middleware.ts
close #245 
@RobbyUitbeijerse How does this work?
@AnatoleLucet Can review?
=> persist middleware to check localStorage

src/middleware.ts
Useful option if you want to omit some fields from persisting.
=> feat: blacklist and whitelist for the persist middleware

src/index.ts, tests/basic.test.tsx
close https://github.com/pmndrs/zustand/issues/276
=> feat: works with useLayoutEffect

src/middleware.ts, src/vanilla.ts, tests/basic.test.tsx
@dai-shi I think this would be a minimal invasive fix for #317 . I can't know for sure until I write some type tests, which is why this is a draft so far :) What do you think?
=> (types): improve types for setState

readme.md
=> updated the immer typescript middleware example to support V9

src/index.ts
close #347 
this would work for deno and jsdom with custom userAgent.
=> fix: better ssr detection

src/middleware.ts
=> fix(persist middleware): incorrect deserialize type

readme.md
suggestion to the readme in order to help avoiding questions such as https://github.com/pmndrs/zustand/issues/355
=> docs: update readme on devtools usage

readme.md
=> docs(readme): fix persist middleware example

readme.md, src/context.ts
=> Removed "initialState" parameter from createContext()

package.json
Discussion - https://github.com/pmndrs/zustand/discussions/407
=> chore: mark react dependency as optional

tests/persistSync.test.tsx
Classic 🙈.  Luckily the tests all pass 😅
=> Remove it.only() from test so that all tests get executed

tests/basic.test.tsx, tests/context.test.tsx, tests/persistAsync.test.tsx, tests/persistSync.test.tsx
... and move one necessary one into the describe() block
=> Remove unnecessary console.error mocks from tests

src/context.ts
(this was my bad in the original snippet. doesn't need lazy initialization pattern.)
=> chore: refactor zustand/context

rollup.config.js
close #200.
can anyone try if this fixes the issue?
=> fix: remove babel runtime dependency

tests/persistSync.test.tsx
This commit extends the test 'can persist state' to not only write state to the storage but to also reinitialise the store afterwards to check if the value would be rehydrated correctly.
=> Extend test case for perist middleware

tests/persistAsync.test.tsx, tests/persistSync.test.tsx
=> Extend test case for async persist middleware

.size-snapshot.json, src/context.ts, tests/context.test.tsx
=> fix(context): stable storeApi

src/middleware.ts, tests/persistAsync.test.tsx, tests/persistSync.test.tsx
Closes #451
This is to follow-up #437 & #442.
=> fix(persist): #451

.size-snapshot.json, babel.config.js, src/index.ts
close #461 
https://codesandbox.io/s/react-forked-bqocl?file=/src/App.js works well.
=> fix: do not use generator to support IE11

src/middleware.ts, tests/persistAsync.test.tsx
Context: https://github.com/pmndrs/zustand/pull/468#issuecomment-869501387
=> fix(persist): merge function not working with async storages

src/middleware.ts
Closes #465 
@n1ru4l can you try this out with the codesandbox below to see if it fixes your issue? :pray: :slightly_smiling_face:
=> fix(persist): incorrect deserialize return type

src/middleware.ts, tests/persistAsync.test.tsx, tests/persistSync.test.tsx
=> fix(persist): not hydrating when the stored item doesn't contain a version

readme.md
=> Update readme.md - Best practices (2 wiki pages)

readme.md
=> Update readme.md best practices jump line

.eslintrc.json, babel.config.js, src/index.ts, tests/basic.test.tsx, tests/context.test.tsx, tests/middlewareTypes.test.tsx, tests/persistAsync.test.tsx, tests/persistSync.test.tsx, tests/types.test.tsx, tsconfig.json
follow https://github.com/pmndrs/jotai/pull/656
and use react-jsx now.
=> chore: update eslintrc and use react-jsx

package.json, src/shallow.ts, tests/basic.test.tsx, tsconfig.json, yarn.lock
following https://github.com/pmndrs/jotai/pull/678
=> refactor: stricter tsconfig

src/middleware.ts
Related to [valtio#229](https://github.com/pmndrs/valtio/issues/229), as they share the same dev tools approach.
=> Fix: remove useless internal info in devtools

.eslintrc.json, package.json, tests/basic.test.tsx, tests/context.test.tsx, tests/middlewareTypes.test.tsx, tests/persistAsync.test.tsx, tests/persistSync.test.tsx, tests/shallow.test.tsx, tests/subscribe.test.tsx, tests/types.test.tsx, tsconfig.json
Following https://github.com/pmndrs/jotai/pull/738
=> refactor(test): use aliases

tests/middlewareTypes.test.tsx
https://github.com/pmndrs/zustand/discussions/619#discussioncomment-1564423
An example from @dumbmatter.
=> chore(tests): more typing example with subscribeWithSelector

readme.md, tests/middlewareTypes.test.tsx
close #632
related #631 
related #619
=> fix(tests): add #632 example and improve middleware types tests

readme.md
=> fix(docs): typing with subscribeWithSelector middleware

tests/middlewareTypes.test.tsx
=> chore(tests): for issue 650

.eslintrc.json, src/middleware/devtools.ts, src/middleware/persist.ts, tests/basic.test.tsx, tests/context.test.tsx
we will be a little more strict about things.
=> chore(eslint): add recommended rules and etc

.github/workflows/test-multiple-versions.yml, .swcrc, package.json, yarn.lock
Use @swc/jest as Jest transformer.
Test run went from 3.703 secs to 2.886 secs. That's about a 22% faster.
=> chore(test): Use SWC as Jest transformer

src/middleware/devtools.ts, tests/devtools.test.tsx
resolve https://github.com/pmndrs/zustand/pull/675#issuecomment-986086807
close #694
=> fix(middleware): devtools work in non-browser

src/middleware/devtools.ts
=> fix(middleware/devtools): deprecate serialize.options

readme.md
=> docs: Fix TypeScript docs for using subscribe with selector

readme.md
=> fix(readme): remove invalid typescript example

docs/typescript.md
Remove unused imports from [typescript docs](./docs/typescript.md)
=> fix(docs): remove unused imports

docs/v4-migration.md
- Fix link for Common Recipes in v4-migration doc
=> fix(docs): fix link for Common Recipes

.codesandbox/ci.json, .github/workflows/lint-and-type.yml, .github/workflows/test-multiple-builds.yml, .github/workflows/test-multiple-versions.yml, package.json, yarn.lock
suggested in https://github.com/pmndrs/zustand/pull/1004#issuecomment-1154430102
=> fix(build): add downlevel-dts

.eslintrc.json, src/context.ts, src/middleware/devtools.ts, src/middleware/persist.ts, src/middleware/redux.ts, src/middleware/subscribeWithSelector.ts, src/react.ts, src/vanilla.ts, tests/basic.test.tsx, tests/context.test.tsx, tests/middlewareTypes.test.tsx, tests/types.test.tsx
following https://github.com/pmndrs/jotai/pull/1234
=> refactor: prefer interfaces

examples/package.json, examples/yarn.lock
1. Remove the dependencies not used in the example site.
2. Move `@testing-library` packages to devDependencies.
=> build(deps)(example): remove used dependencies

examples/src/components/CopyButton.js, examples/src/utils/copy-to-clipboard.js
Refactor copyToClipBoard function with the latest version of clipboard API
=> refactor(example): updated with the latest version of the clipboard API

examples/src/components/CopyButton.js
In this PR we worked on the correct cleaning of timeOut and useCallback was added
=> fix(example): clearTimeout and useCallback was added on CopyButton

docs/typescript.md
=> doc(types): Remove independent slices pattern

src/shallow.ts
=> fix(shallow): restrict types

docs/event-handler-in-pre-react-18.md, readme.md
=> fix(docs): add a note for TS users and update links to docs

examples/package.json, examples/src/components/CodePreview.js, examples/yarn.lock
This fix the unexpected font changes, the issue is described in #1096.
=> fix(example): unexpected font changes

src/shallow.ts, tests/shallow.test.tsx
=> fix(shallow): types with useStore again

src/context.ts, src/middleware/combine.ts, src/middleware/devtools.ts, src/middleware/immer.ts, src/middleware/persist.ts, src/middleware/redux.ts, src/middleware/subscribeWithSelector.ts, src/react.ts, src/vanilla.ts
https://github.com/pmndrs/zustand/pull/1089#issuecomment-1186511123
=> fix(types): avoid using deprecated types

docs/persisting-store-data.md
Add context for TypeScript users. Related to https://github.com/pmndrs/zustand/issues/1127#issuecomment-1193922792
=> fix(docs): Update persisting-store-data.md

docs/practice-with-no-store-actions.md
=> docs: move practice-with-no-store-actions wiki page into docs

docs/3rd-party-libraries.md, docs/auto-generating-selectors.md, docs/event-handler-in-pre-react-18.md, docs/flux-inspired-practice.md, docs/immutable-state-and-merging.md, docs/introduction.mdx, docs/maps-and-sets-usage.md, docs/persisting-store-data.md, docs/practice-with-no-store-actions.md, docs/recipes.mdx, docs/testing.mdx, docs/typescript.md, docs/updating-nested-state-object-values.md, docs/v4-migration.md, docs/zustand-v3-create-context.md
copy files from website repo (except for libraries.mdx)
should merge before https://github.com/pmndrs/website/pull/240
this pr doesn't change the content, we should update it too later.
=> docs: move mdx files from website repo

docs/introduction.mdx, docs/recipes.mdx
=> docs: Made minor fix for the recipes 

src/middleware/devtools.ts
=> fix(types)(middleware): use official Config type for options

src/vanilla.ts
=> fix(types): typo in jsdoc and follow-up #1144

src/middleware/devtools.ts
=> fix(types)(middleware/devtools): copy devtools option types instead of importing

readme.md
Updates link to look in the guides directory
=> Fix TypeScript docs link

docs/getting-started/comparison.md
Fixes #1008 
Adding missing change on comparison section
=> fix(docs): comparison

tests/basic.test.tsx, tests/context.test.tsx, tests/persistAsync.test.tsx
following https://github.com/pmndrs/jotai/pull/1396
=> chore(tests): enable StrictMode as much as possible

docs/guides/typescript.md
Fixes failing build here: https://github.com/pmndrs/website/pull/251
=> fix: remove unneeded <br> causing website build to fail

docs/getting-started/comparison.md
Line 19: you -> your
1 Fix.
Fixed the grammar mistake on line 19 (missing r). Proof read the comparison and everything else is grammatically correct.
=> Fixed grammar in comparison.md

tests/persistSync.test.tsx
=> refactor(test): rename persistent

docs/getting-started/comparison.md
docs: Remove redundant words.
Fixes #.
=> docs: Remove redundant words.

docs/integrations/persisting-store-data.md
=> Spelling correction

docs/guides/slices-pattern.md
=> Docs: added section in slices-pattern explaining how to affect multiple stores in one function

docs/guides/auto-generating-selectors.md
=> docs: bumped zustand to latest version (4.1.4) for CodeSandbox example in auto generating selectors doc

docs/integrations/3rd-party-libraries.md
Adds my zustand-computed library, which is updated to match the latest API version and supports the proper typing like detailed in your examples.
=> Add zustand-computed to 3rd-party-libraries.md

docs/integrations/persisting-store-data.md
Fixes #1510 
Update doc to include how to handle Map and Set with the new persist API.
issue since i have yarn v3 installed, it creates `.yarn` and `.yarnrc.yml` and need me to set pacakge to v1 with `yarn set version classic` so not sure i can run prettier easily but i will run it and delete the files we don't want commited.
=> doc: update documentation of persist

rollup.config.js
=> fix(vanilla,shallow): default export regression in CJS

examples/demo/package.json, examples/demo/src/App.js, examples/demo/src/resources/code.js, examples/demo/yarn.lock
Fixes #1548.
zustand 4.3 deprecates default export.
=> fix(examples): use named exports in demo

CONTRIBUTING.md
Updates #1580.
As promised, I've done some cleanup in the contributing guide.
=> Reformat and fix typos, extend the committing guide in the contributing guide

package.json
following https://github.com/pmndrs/valtio/pull/649
=> fix(build): improve patch scripts

docs/integrations/third-party-libraries.md
Fixes #.
This PR includes to the docs a new Library I'm creating for Angular applications which adapts Zustand vanilla to be used in angular application in a simple and easy way.
https://github.com/JoaoPauloLousada/ngx-zustand
=> Include "ngx-zustand" to third-party-libraries.md

rollup.config.js
following https://github.com/pmndrs/jotai/pull/1780
=> fix(build): possibley improve ESM for production build

docs/integrations/third-party-libraries.md
None
Fixes #
None
Docs: added 'Zukeeper,' new open source devtools for Zustand, to list of third-party libraries
- [ x ] `yarn run prettier` for formatting code and docs
=> Added to third-party libraries

docs/integrations/persisting-store-data.md
Fixes #
Example needs createJSONStorage to run, but it isn't imported
=> fix(docs): Update imports

readme.md
=> fix(docs): broken testing doc link

examples/demo/package.json, examples/demo/yarn.lock
none
fixed the issue of sample startup failure
when i tried to start the demo, i got this error:
```error
Compiled with problems:X
ERROR
[eslint] Failed to load parser '@typescript-eslint/parser' declared in 'package.json » eslint-config-react-app#overrides[0]': Cannot find module 'typescript'
```
so i fixed that
=> fix: sample startup failure issue fix

rollup.config.js
It's a bug I made in the last commit of #1789: https://github.com/pmndrs/zustand/pull/1789/commits/17cd48fa0986c394ed4dec6b07dc69a50b6783b6
=> fix: rollup config

readme.md
Added [pnpm](https://pnpm.io/) as install option
=> Update readme.md: add pnpm as install option

docs/integrations/third-party-libraries.md
#1842 
Add use-broadcast-middleware to the third-party libs.
It's a cross-tab sharing middleware for Zustand, it also export a simple hook.
=> docs: added a new third party lib

docs/integrations/third-party-libraries.md
Adds [zustand-ards](https://github.com/ivoilic/zustand-ards) to the third-party libraries list
=> Added zustand-ards to the third-party libraries list

docs/previous-versions/zustand-v3-create-context.md
Update comment //store.ts to //store.tsx in zustand-v3-create-context.md
=> Update comment //store.ts to //store.tsx in zustand-v3-create-context.md

docs/guides/testing.md
Fixes couple minor  issues on testing docs
=> Testing docs minor fixes

readme.md
Fixed some grammar and punctuation
=> 📝 Fixed some grammar and punctuation

rollup.config.js, src/middleware/devtools.ts
follows https://github.com/pmndrs/jotai/pull/1978
fixes #1840
=> fix(build): mode env for "import" condition"

docs/guides/flux-inspired-practice.md
=> Fix `slices-pattern.md` link on `flux-inspired-practice.md`

docs/integrations/persisting-store-data.md
=> docs: add missing import to persisting store data TypeScript usage

docs/guides/testing.md
Improve testing docs
- Add examples about how to test out `zustand` when you use `createStore()` and `useStoreWithEqualityFn()`
- Update previous examples to share state creator between examples
- Update packages and configs on codesandbox examples
=> Update testing docs

.gitignore
https://github.com/pmndrs/zustand/discussions/2014#discussioncomment-6837085
https://github.com/pmndrs/zustand/discussions/2014#discussioncomment-6837085
Fixes #
Updated .gitignore
=> Ignored pnpm-lock.yaml as discussed

.gitignore, docs/integrations/third-party-libraries.md
Fixes #
Added third party integration
- [persist-and-sync](https://www.npmjs.com/package/persist-and-sync) - Zustand middleware to easily persist and sync Zustand state between tabs / windows / iframes (Same Origin)
=> Persist and sync

docs/guides/testing.md
No issues related
Update zustand jest codesandbox demo
=> Update zustand jest codesandbox demo

docs/previous-versions/zustand-v3-create-context.md
Fixes https://github.com/pmndrs/zustand/discussions/1276#discussioncomment-6953472
The migration doc was misguiding.
=> fix(docs): zustand v3 context migration doc

docs/guides/how-to-reset-state.md
Fixes #2116
Update reset state docs
=> Update reset state docs

readme.md
For more information, see https://github.com/pmndrs/zustand/discussions/2200
Fixes #2200 
Add a warning to readme about React Server Components
=> Add a warning to readme about React Server Components

package.json, yarn.lock
Fixes #
Immer 9.0.5 < has a security issue that is critical. https://github.com/immerjs/immer/commit/fa671e55ee9bd42ae08cc239102b665a23958237
=> chore(immer): fix security issue

package.json, rollup.config.js
for #2138 
It follows Jotai and Valtio.
This change may help user and editor to avoid confusion.
=> [v5]: separate react entry point

src/react.ts
https://github.com/pmndrs/zustand/pull/2328#discussion_r1490991168
=> chore: clarify deprecation message

docs/guides/slices-pattern.md
Fixes #2376.
As mentioned, I started adding a note to discuss with @dbritto-dev about using middlewares in slices.
=> docs: adding note about middlewares and slices

tests/devtools.test.tsx
=> chore(tests): suppress expected warnings

docs/guides/nextjs.md
=> Fixing typo in nextjs.md

docs/integrations/third-party-libraries.md
Add https://github.com/zustandjs/zustand-slices in the third-party lib list.
=> docs: add zustand-slices

docs/guides/updating-state.md
None
Since [Ramda](https://ramdajs.com/) offers [`modify`](https://ramdajs.com/docs/#modify) and [`modiyPath`](https://ramdajs.com/docs/#modifyPath), this might be an easier way to do deep object modification.
=> docs: update ramda example

examples/demo/.eslintrc.cjs, examples/demo/.prettierrc, examples/demo/package.json, examples/demo/src/components/CodePreview.jsx, examples/demo/src/components/Details.jsx, examples/demo/src/components/Fireflies.jsx, examples/demo/src/components/Scene.jsx, examples/demo/src/materials/layerMaterial.js
- fix eslint config and lint issues
- fix react key issue
- remove children passed as props
- remove unused variables and imports
- "encodings_fragment" is deprecated, replaced it with "colorspace_fragment"
=> update: example/demo

docs/integrations/third-party-libraries.md
Fixes #
Added a library in the list of third party integrations
=> doc: added treeshakable to external libraries

.github/workflows/compressed-size-action.yml, .github/workflows/lint-and-type.yml, .github/workflows/publish.yml, .github/workflows/test-multiple-builds.yml, .github/workflows/test-multiple-versions.yml, .github/workflows/test-old-typescript.yml
Upstream: https://github.com/pnpm/action-setup/issues/135#issuecomment-2206861174
=> ci: fix pnpm setup

.github/workflows/test-old-typescript.yml, tests/basic.test.tsx, tests/context.test.tsx, tests/devtools.test.tsx, tsconfig.json
following https://github.com/pmndrs/jotai/pull/2664
=> chore: enable verbatimModuleSyntax in tsconfig

.github/workflows/docs.yml
https://github.com/pmndrs/docs/pull/288
=> website: add github link

docs/getting-started/introduction.md
https://docs.pmnd.rs/getting-started/authoring#img:~:text=You%20are%20encouraged%20to%20use%20relative%20images%2C%20since%20dimensions%20are%20automatically%20added%20as%20img%5Bwidth%5D%5Bheight%5D%20attributes.
=> relative images as much as possible

.github/workflows/test-old-typescript.yml, package.json, pnpm-lock.yaml, tests/test-utils.ts, tsconfig.json
following https://github.com/pmndrs/jotai/pull/2687
=> chore: enable isolatedDeclarations

docs/migrations/migrating-to-v5.md
=> chore: v5 migration docs

docs/integrations/third-party-libraries.md
Adding my third-party lib to the list...
=> docs: add `zutron` to third-party-libs

docs/integrations/third-party-libraries.md
Fixes #
Added my zustand-hash-storage library into docs (third-party-libraries.md)
=> Update third-party-libraries.md (add zustand-hash-storage)

docs/apis/create-store.md, docs/apis/create-with-equality-fn.md, docs/apis/create.md, docs/apis/shallow.md, docs/hooks/use-shallow.md, docs/hooks/use-store-with-equality-fn.md, docs/hooks/use-store.md, docs/middlewares/combine.md, docs/middlewares/devtools.md, docs/middlewares/immer.md, docs/middlewares/persist.md, docs/middlewares/redux.md, docs/middlewares/subscribe-with-selector.md
=> Update docs content

docs/integrations/third-party-libraries.md
Fixes #
Add zustand-lit to third party libs.
=> chore: update third-party-libraries.md

.eslintrc.json, package.json, pnpm-lock.yaml, tests/basic.test.tsx, tests/persistAsync.test.tsx, tests/shallow.test.tsx, tests/ssr.test.tsx
Testing Library provides [Eslint plugin ](https://testing-library.com/docs/ecosystem-eslint-plugin-testing-library) which encourages to use best practices.
=> test: incorporate eslint-plugin-testing-library and fix reported issues

docs/guides/testing.md
change filename: `user-counter-store.ts` -> `use-counter-store.ts`
change module directory: `// stores/counter-store-creator.ts` -> `// shared/counter-store-creator.ts`
Fixes #
=> chore(docs): fix typo

docs/middlewares/devtools.md
Fix the link to devtools new repository
=> chore(docs): Fix the link to devtools

.github/workflows/compressed-size-action.yml, .github/workflows/docs.yml
* unify format style in .github/workflows files
=> chore(.github/workflows): unify format style

package.json, rollup.config.mjs
* Relate with https://github.com/pmndrs/zustand/pull/2939
=> chore(rollup): migrate commonjs to esmodule

docs/guides/tutorial-tic-tac-toe.md
Used separate selector individual selectors for ```squares``` and  ```setSquares```.
=> docs(tutorial-tic-tac-toe.md): fix code to prevent infinite loops

docs/guides/tutorial-tic-tac-toe.md
=> chore(docs): update tutorial tic tac toe

docs/integrations/persisting-store-data.md
Fixes #
Fixed a small mistake in the persist example and added another example for typescript.
- [ x] `pnpm run fix:format` for formatting code and docs
=> fixed error in persist example and added typescript

docs/integrations/persisting-store-data.md
=> docs: fix typo in type

docs/middlewares/devtools.md
=> docs: fix devtools example

docs/integrations/third-party-libraries.md
Adding custom Zustand middleware to share state across state via [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)
=> doc: Added use-post-message-ts to third party

docs/integrations/third-party-libraries.md
Fixes #
Added zustand-namespaces to docs for 3rd party
=> docs: added zustand-namespaces to 3rd party

src/middleware/combine.ts
* Relates with https://github.com/pmndrs/jotai/pull/3002#pullrequestreview-2640696617
=> refactor(middleware/combine.ts): change exported function to 'function declaration'

README.md
* Relates https://github.com/pmndrs/valtio/pull/1079
=> docs(README.md): change build badge url

docs/guides/tutorial-tic-tac-toe.md
Replaced setSquares with onPlay in the handleClick function of the Board component
=> docs: update tutorial

docs/apis/create-with-equality-fn.md, docs/hooks/use-store-with-equality-fn.md
=> docs: update createWithEqualityFn and useStoreWithEqualityFn docs

docs/guides/auto-generating-selectors.md
=> docs: Prefer const to let (auto generating selectors)

docs/apis/create-with-equality-fn.md, docs/apis/create.md
fix the usage error of setPosition
=> docs: fix the usage error of setPosition

docs/guides/testing.md, docs/llms.txt, docs/middlewares/devtools.md, docs/middlewares/immer.md
=> docs: general docs improvements

package.json
following https://github.com/pmndrs/jotai/pull/3042
related discussions:
- #1967 
- #3089 
- #3090
=> fix(package): react-native condition

tests/vanilla/basic.test.ts
=> test(vanilla/basic): add test for 'getInitialState'

docs/guides/testing.md, tests/persistAsync.test.tsx, tests/persistSync.test.tsx
=> chore: fix some typos in comment

docs/middlewares/redux.md
=> docs: update redux api docs

src/react.ts
Fixes https://github.com/pmndrs/zustand/discussions/971#discussioncomment-13899232
Micro optimization for stable selectors.
=> fix(react): useCallback for getSnapshot

docs/apis/create-store.md
Fixes #
Found non-functional links in the document's table of contents of document. Fixed the broken internal links.
=> fix broken links in the toc of create-store.md

eslint.config.mjs
follow https://github.com/pmndrs/valtio/pull/1163
=> chore: strict unused check

docs/integrations/third-party-libraries.md
[#3219 - Add createSetterFn to the library](https://github.com/pmndrs/zustand/pull/3219)
Fixes https://github.com/pmndrs/zustand/pull/3219#issuecomment-3227131283
=> Add new Zustand third-party links for `zustand-create-setter-fn` and `zustand-utils`
