pmndrs/zustand

- .size-snapshot.json
- src/index.js
- tests/test.js
The code this library currently uses to shallow check state equality has a potential bug.
```js
if (sliceRef.current !== selected && selected === Object(selected)) {
selected = Object.entries(selected).reduce(
(acc, [key, value]) =>
sliceRef.current[key] !== value
? Object.assign({}, acc, { [key]: value })
: acc,
sliceRef.current
)
}
```
In the event that sliceRef.current has a property that was later deleted in a global state update, this ghost property would remain in the new selected which can cause issues if the component has logic that depends on the presence or absence of that property.
Example:
```js
let test = (prevState, newState) => {
if (prevState !== newState && newState === Object(newState)) {
newState = Object.entries(newState).reduce(
(acc, [key, value]) =>
prevState[key] …
```
> Switched to a better battle tested shallowEquality check

- readme.md
Small typo `Receipes` should be `Recipes`
> Updating typo in README

- .size-snapshot.json
- package.json
- src/index.ts
- tests/test.tsx
Just minor updates. Adding a test for `destroy` made me question something. The store can be used after `destroy` is called. Is this expected behavior?
Also, I did not update the package.json version. I noticed `yarn publish` gives you the option to bump the version when deploying the package so I figured I would leave that to @drcmda
> Update refs in useEffect, add more tests, fix pre-commit lint

- .size-snapshot.json
- src/index.ts
- tests/test.tsx
The latest selector was only used in the subscribe callback. It should also be used when `useStore` is called. Should fix #18.
This change should be reviewed and tested by others (@drcmda, @timkindberg) to make sure it actually fixes the issue and does not cause regressions. I only added one test.
> Update state slice when selector changes

- src/index.ts
Fixes #21 
Exports a few types for usage outside of the module and adds default types for generics.
> Improve Typescript types and generics

- .size-snapshot.json
- readme.md
- src/index.ts
- tests/test.tsx
Fixes #24 and adds feature #23.
This was a bit more painful than I thought it would be. Expected changes were made to `setState` and `subscribe`. Unexpected changes were made to `useStore`. For performance reasons, I decided to not use `getState` as a default selector if none is passed in. If I didn't do this, a `shallowEqual` check would be performed on the entire store for components that use `useStore` without a selector. This led to a cascade of required changes that should be tested more thoroughly.
Additionally, I removed the `state = {}` in `destroy` due to the fact that it invisibly breaks the store when using TypeScript (Type is still `TState` but value is `{}`). External references to the store or objects in the store still won't be garbage collected if they can be reached so …
> Add selector to api.subscribe

- .size-snapshot.json
- src/index.ts
Replace useLayoutEffect to useEffect in server side not to print below error message.
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
```
https://github.com/react-spring/zustand/issues/11
> Replace useLayoutEffect to useEffect in server side to fix ssr issue

- .size-snapshot.json
- package.json
- readme.md
- rollup.config.js
- src/index.ts
- tests/test.tsx
- yarn.lock
equality: https://github.com/react-spring/zustand/issues/36
try/catch: https://github.com/react-spring/zustand/pull/37
all tests seem to work, docs are updated
This would be a breaking change (major) since the useStore fn signature was slightly adjusted, removing dependencies (which are pretty much useless ever since we merged @JeremyRH's referened-selectors) in favour of an optional equality function.
It also adds basic middleware officially.
zustand defaults to strict-equality (old === new) to detect changes, this is efficient for atomic state picks. 
```jsx
const foo = useStore(state => state.foo)
const bar = useStore(state => state.bar)
```
If you want to construct a single object with multiple state-picks inside, similar to redux's mapStateToProps, you can tell zustand that you want …
> 1.x (optional equalityFn, error safe selectors, middleware: redux & devtools)

- .size-snapshot.json
- rollup.config.js
- src/index.ts
Hey! I have a need to drop zustand into a tampermonkey script, but there was no UMD build. I'm not a huge fan of UMD and it seems like you're trying really hard to keep the bytes down so I went with IIFE.
I added 'create' to the exports because `zustand.default(set =>...)` is ick. It increases your bundle sizes, though. I don't mind either way.
> Add IIFE build

- src/index.ts
Should solve #45. We lose inference when not passing in the state though (defaults to `Record<string | number | symbol, any>`).
@jfbrazeau
> Remove manual check of passed State generic

- .size-snapshot.json
- src/index.ts
- tests/test.tsx
React may sometimes batch updates (e.g. event listeners, maybe more in future). The current implementation of `forceUpdate` does not work when an even number of updates are batched. The added test fails on master.
> Support batched updates

- src/index.ts
This improvement will help with type inference when using `useStore` without selectors.
For example
```
import create from 'zustand'
interface IState {
count: number;
increase: () => void;
reset: () => void;
}
const [useStore] = create<IState>(set => ({
count: 0,
increase: () => set(state => ({ count: state.count + 1 })),
reset: () => set({ count: 0 })
}));
function Counter() {
const { count, increase, reset } = useStore()
// typeof count === 'number' => true
// typeof increase === 'function' => true
// typeof reset === 'function' => true
return <h1>{count}</h1>
}
```
> Adjust type inference for store without a selector

- .size-snapshot.json
- package.json
- src/index.ts
- tests/test.tsx
I uncovered a couple issues that lead to these changes. Sparse arrays (arrays with holes) seem to have poor performance when their length grows too large (even if they are empty). I wasn't limiting the subscriber counter so it would potentially assign a large index to the subscribers array and cause the `forEach` loop in `setState` to have performance issues. I fixed that by consolidating the subscribers array during `setState`. This minimally impacts performance for every call to `setState` and greatly improves performance in applications that are long running and/or have many renders per second.
The changes lead to a small refactor and unfortunately, some types changed. Good news is these types are used for internal functionality so our public API hasn't changed.
I also found an issue …
> 2.1.x // Type changes and perf/bug fixes.

- readme.md
Not sure if this was a typo or intended? I couldn't find any reference to useBuerli elsewhere in the project
> replace useBuerli with useStore in readme

- .size-snapshot.json
- src/shallow.ts
As the title says.
`useStore` also infers the return type via `EqualityChecker<U>`, so the current types of `shallow` would always make TypeScript infer the return type as `any`.
This PR adds more constraints to `obj1` and `obj2` in `shallow`.
> Fix type inference of TypeScript for `shallow` by removing `any`

- .size-snapshot.json
- src/index.ts
- tests/test.tsx
@jhgg
Should fix #84 
Here was the problem:
- Subscriber object is created during the render phase and its index is assigned.
- `setState` is called before the subscriber object is added to `subscribers` array (between render phase and `useLayoutEffect`).
- `subscribers` array is made dense, changing the length of the array and indices of subscribers.
- Subscriber object is added to `subscribers` array at wrong index, overwriting a valid subscriber.
I moved the code that makes `subscribers` a dense array into the "unmount" phase (return function of `useLayoutEffect` callback).
> Fix subscriber being overwritten

- .size-snapshot.json
- src/index.ts
- tests/test.tsx
Should fix #86 
@karlpetersson Sorry for submitting a separate PR instead of working off yours. I wanted to simplify the logic if we plan on removing the attempt to support concurrent mode. I also added a test.
Thank you @karlpetersson for the help and you did find a fix which I used here.
> Fix subscribers being overwritten between render and effect

- src/index.ts
> Fix typing of PartialState<T> for immer usage

- package.json
- src/index.ts
- tests/test.tsx
- yarn.lock
This is for next major version.
Some notes:
- It will only work with react@experimental, it may change later, and we are not sure when it will be finalized.
- It's based on useMutableSource, and no longer requires useEffect and useRef.
- The render behavior is slightly changed.
- The behavior with exception is changed. The spec is skipped.
- [IMPORTANT] selectors and equalityFn should be stable. Either make them static or wrap with `useCallback`.
- However, thanks to scoped subscription (unlike Redux), unstable selectors seem to work.
- On the other hand, it needs to cache the selector result `cachedSlices`, which is a bit hacky.
- `functionMap` is hacky too, but can't be helped.
- Needs someone to review the changes in tests, if they are valid or not.
- Bundle size is increased a bit, …
> feat: new implementation with useMutableSource

- .size-snapshot.json
- src/index.ts
- tests/test.tsx
useMutableSource version doesn't require subscriber, so this simplifies a lot.
Note, this is technically a braking change in the exported types.
I assume people are not extensively using `ApiSubscribe` type in v2.
> [v3-alpha] clean up types

- .size-snapshot.json
- src/index.ts
- tests/test.tsx
Breaking change!!!
before:
```js
const [useStore, api] = create(...)
```
after:
```js
const useStore = create(...)
const api = useStore // if you need
```
OR
```js
const store = create(...)
store.getState()
const value = store.useStore(...)
```
> [v3-alpha] unified api

- .size-snapshot.json
- src/index.ts
- tests/test.tsx
- eliminate subscriber so that we can extract vanilla version
- unified api with backward compatible tuple (no type)
Important notes:
- It will call selector once more at subscribe due to caching at the both ends
- This is a bit unfortunate, but it's more consistent with v4-alpha
- The use of `useCallback` for selector and equalityFn is highly recommended
- Or define the function outside render
- It will be optimized with ref equality
- This is also the case with v4-alpha
- Without `useCallback`, it will still work, can be slow but not noticable in small apps.
> [v3] eliminate subscriber + unified api

- .size-snapshot.json
- src/index.ts
- tests/test.tsx
This will refactor subscribe and clean up code quite a bit.
This is technically a breaking change. Exported types are a bit changed.
----
#139 
> It will call selector once more at subscribe due to caching at the both ends
This hack is gone. See the test spec is reverted.
#114
> We could revisit this in v3
Because, we don't have selector in subscribe. No throwing error. Cleaner listener typing.
> [v3] add slim subscribe and refactor useStore

- src/middleware.ts
If a prefix is provided, it will be used as the instance name. If one is not provided, the default devtools behaviour will be used.
> Uses prefix as devtools instance name

- readme.md
I don't know if it's really a typo or so (it seems that yes, because I don't know where `foo` and `bar` comes from), so it fix the README comments to be more understandable. As far as I understood the shallow diffing, it seems that the comments are wrong.
Great library by the way, loving the usage and the concise API!
> README typo

- .size-snapshot.json
- src/index.ts
There's an edge case where state is changed between when a hook is used in the render phase and when a hook subscribes to a store in the commit phase.
> fix: detect state change before subscription

- .size-snapshot.json
- src/middleware.ts
Close #77 
- devtools follows v3 api (`replace` flag)
- devtools works without `name` (defaults to `action`)
- type devtools and redux middleware (a bit messy, can improve?)
Here's how you could use devtools in TS.
```ts
const useStore = create<{
count: number
increment: () => void
decrement: () => void
}>(devtools((set, get) => ({
count: 0,
increment: () => set({ count: get().count + 1 }, false, "inc"),
decrement: () => set({ count: get().count - 1 }, false, "dec"),
})));
```
Here's redux middleware in TS.
```ts
const initialState = {                                                          
grumpiness: 0,                                                                
}                                                                             
const reducer = (  
state: typeof …
```
> fix devtools and type middleware properly

- src/vanilla.ts
Close #96 
The fix in #99 doesn't seem correct. https://github.com/react-spring/zustand/issues/96#issuecomment-673764960
This would be a better fix. Although this reverts #99, I couldn't get response in #96, so let's publish it and see how it works.
Here's immer recipe in TS without middleware.
```ts
interface State {
lush: {
forrest: {
contains: { a: string } | null
}
}
set: (fn: (s: State) => void) => void
}
const useStore = create<State>((set) => ({
lush: { forrest: { contains: { a: "bear" } } },
set: (fn) => set(produce(fn)),
}))
const a = useStore((state) => state.lush.forrest.contains?.a)
const set = useStore((state) => state.set)
set(state => {
state.lush.forrest.contains = null
})
```
Here's the recipe with middleware.
```ts
connst immer = <T>(
config: StateCreator<T, (fn: (state: …
```
> fix typing for immer

- .size-snapshot.json
- src/middleware.ts
Close #171. 
~There are a few technical issues:~
~1. we need to fix types in vanilla.ts and index.ts too.~
~2. we can't chain middleware that only patches `set`.~
~Due to 2), I'm a bit hesitant to this approach.~
> fix: devtools to patch api.setState

- .size-snapshot.json
- src/index.ts
- src/middleware.ts
- src/vanilla.ts
- tests/test.tsx
Close #95 
This adds a new piece of middleware.
This also avoids `any` (which is a breaking change in types, but not in behavior.)
```ts
import create from "zustand";
import { combine } from "zustand/middleware";
const useStore = create(combine({
count: 0,
text: "hello",
}, (set) => ({
inc: () => set((state) => ({ count: state.count + 1 })),
setText: (text: string) => set({ text }),
})));
```
> Stricter types

- tests/test.tsx
Fix typo when defining the equality function in test `can use exposed types`
> Fix(tests.tsx) typo in equalityFn definition

- readme.md
I was wondering if the `subscribe` function also supports an equality function as third parameter. Of course it does! But I had to look it up in the code – so I thought adding it to the readme might be helpful.
> Readme: Add docs for subscribe equality function

- .size-snapshot.json
- src/index.ts
Close #123 
There was a bug. It ignores state updates when react rerenders before zustand propagates updates.
Thanks  @andrew-me for reporting this.
> fix: evaluate selector if state is changed

- src/middleware.ts
I recently started using Zustand with next.js for my client-side state. In order to better debug/track the state, I've also started using the devtools middleware. This works fine on the client-side (in the browser), but results in lots of `console.warn` lines server-side (in the terminal when running the development server) stating "Please install/enable Redux devtools extension", which can obscure actual messages at times due to the number of times it is output. As the server side rendering happens outside of a browser, it seems a safe enough condition to add to this if statement.
The only other alternative I found to fix this locally is to assign the result of `create()` or `create(devtools())` conditionally, which results in a lot of duplicate code, as the devtools middleware requires …
> Hide warning when not run in browser (middleware)

- readme.md
add ramda's pipe middlewares example as discussed [here](https://github.com/pmndrs/zustand/discussions/224)
```js
import create from "zustand"
import produce from "immer"
import pipe from "ramda/es/pipe"
const log = config => (set, get, api) =>
config(
args => {
console.log("  applying", args)
set(args)
console.log("  new state", get())
},
get,
api
)
// Turn the set method into an immer proxy
const immer = config => (set, get, api) =>
config(fn => set(produce(fn)), get, api)
const createStore = pipe(log, immer, create)
const useStore = createStore(set => ({
bears: 1,
increasePopulation: () => set(state => ({ bears: state.bears + 1 })),
}))
export default useStore
```
> add pipe middlewares example

- readme.md
Small thingy, the `StateCreator` import was missing in the "How to type immer middleware in TypeScript" example.
> Fix missing import in readme example

- readme.md
- src/middleware.ts
Hi :wave: I saw [this comment](https://github.com/pmndrs/zustand/issues/214#issuecomment-715895730) so I've decided to open a pr for the middleware I've made and shared [here](https://github.com/pmndrs/zustand/issues/76#issuecomment-670367631).
I've been using it for multiples months on a project at work, and it actually works nicely given its simplicity.
But I still think there's some quite annoying drawbacks that we could probably improve:
- The obligation to give a name to the middleware. It'd be preferable to not hard code the name so the middleware could generate unique names/ids for the user. But I can't come up with a way to do this. 
- Rehydration & merge & update of a stored state that has changed since. I don't think this is possible (?), but it still'd be nice to erase the old …
> feat: add persist middleware

- tests/basic.test.tsx
We had a discussion about equality check in #234.
Unfortunately, two opinions are simply conflicting.
@JeremyRH I made a test to illustrate why I think the current behavior is intuitive for me.
FWIW, react-redux's implementation should be the same behavior.
https://github.com/reduxjs/react-redux/blob/94fcab6002989f1e106d6edd1b41dbd6599e6785/src/hooks/useSelector.js#L60-L64
> add equality check test

- readme.md
- src/vanilla.ts
- tests/basic.test.tsx
Decided to go ahead with my proposal of #240. I found the second argument was used for the error in case there's an error, but that's undocumented, so I am not sure how much of a breaking change this would be.
> Expose previous value in subscribe

- src/middleware.ts
Allows for persisting the store when using the api.setState method.
Related issue: https://github.com/pmndrs/zustand/issues/238
> Persisting when using the api.setState() method

- readme.md
This was discovered because I defined my state with a bunch of `readonly`s and receiving the error that the property wasn't updated.
See also: https://immerjs.github.io/immer/docs/typescript
> Use Draft<T> in immer typescript middleware

- src/middleware.ts
A callback after ~~persisting~~ rehydration may be helpful.
E.g. in the scenario below, where I need to prevent unnecessary redirection before the store ~~persisting~~ rehydration is done.
```javascript
const PrivateRoute: React.FC<RouteProps> = React.memo((props) => {
const hasSession = useSessionStore(selectHasSession);
if (hasSession) {
return <Route {...props} />;
}
return <Redirect to={RootRoutes.LOGIN} />;
});
```
The initial store looks like that:
```javascript
const store = (set: SetState<State>) => ({
loading: false,
hasSession: false,
login: loginAction(set),
logout: logoutAction(set),
});
```
So in the initial state I have the `hasSession` field set as `false`, and after the store rehydration it will change to `true`. This case implies the unnecesary redirection before the …
> feat: callback after persist

- src/vanilla.ts
- tests/basic.test.tsx
Typescript could not properly infer type of newState in state equality function.
```js
//new is typed as unknown giving type errors
const state = useSomeState(s => s.item, (oldItem, newItem) => oldItem.id === newItem.id)
```
After that change above snippet compiles and works properly.
> fixed an issue in type infering while using eq function in hooks

- readme.md
Minor spelling change: "forrest" corrected to "forest".
> Update readme.md (minor spelling fix)

- readme.md
The `State` typing provided to the `create` function must extend `Record`. Thus, the `State` typing that users provide needs to be a `type` and not an `interface`. This PR adds a small comment in the TS Recipe to make that clear.
Closes #213 
- Add comment in TS recipe's codee
- Github markdown preview
> docs: add comment regarding TS State typing

- readme.md
This PR adds a testing section in `README.md`, showcasing how someone can make sure that all of the tests run with the same (pristine) `zustand` store state.
The pattern includes mocking the original `zustand` export and replacing it with a "mocked" version that automatically resets all stores after each test. This pattern has been showcased for `jest`, but it can easily be extended to other test runners as well.
- Add testing section in README
- Github Markdown Preview
> docs: add testing section

- src/middleware.ts
- add js doc for option object
- improve ssr support
- add a new version option #243
- refactor postRehydrationMiddleware to onRehydrateStorage
---
This ended up being more of a feature rich pr instead of a full refactor :smile:
Anyway this includes the two breaking changes I intended to add. The callback for the `storage` options, and the new `onRehydrateStorage` option.
I intend to add some more features on this middleware (I'll open a few issues soon), but no breaking changes in mind.
Close #248
Close #243
> feat(persist): improve ssr & add versions & new callback

- src/middleware.ts
Closes #283 
This warning doesn't cover `api.setState`, but I'm not sure if it really needs to.
> feat(persist): add warn if storage is unavailable

- readme.md
> docs: add an example for setting the state outside event (#302)

- .codesandbox/ci.json
- .gitignore
- .size-snapshot.json
- package.json
- rollup.config.js
- src/middleware.ts
- yarn.lock
Hi there!
I made a [PR for jotai](https://github.com/pmndrs/jotai/pull/378) a few days ago updating the build tooling to use esbuild as the typescript transpiler and @dai-shi requested I make PRs for zustand and [valtio](https://github.com/pmndrs/valtio/pull/129), so here we are! The main reason for this change is because of how much faster esbuild is at compiling javascript from typescript:
Before
✨  Done in 25.26s.
After
✨  Done in 6.80s.
There are also some very minor bundle size changes with this update.
- added `esbuild` and `rollup-plugin-esbuild`
- replaced the `typescript` plugin in `createESMConfig`, `createCommonJSConfig`, and `createIIFEConfig` to use esbuild
- added `id.includes('@babel/runtime')` to the externals check [per this …
> build: use esbuild

- readme.md
Hey!
Although I had already used `shallow`, It took me a while to notice the second argument on the store hook was an equality function, I found it out later reading the typedefs.
I think it would be a good idea (especially for dumb readers like me) to state it more explicitly: "the second argument is an equality function, it has this signature".
Here goes a suggestion. Thank you!
> Readme: be more explicit about equality function

- package.json
- rollup.config.js
- yarn.lock
It seems like our trial (`'bundled'`) in #343 was not successful.
We can revisit it, but for now we should fix v3.4.0.
This reverts babel config for CJS to that in v3.3.3. Resolve #351.
> fix: revert babel runtime

- readme.md
@dai-shi requested we add a wiki page containing a list of 3rd-party libs that work with zustand. I have added a link to the readme.md to the wiki page by copying the style used to link to the testing wiki page.
Please give me any comments or critiques!
> update readme.md to link to the 3rd-party wiki

- .size-snapshot.json
- src/middleware.ts
Currently it is possible to export the state of the store in redux devtools, but it is not possible to import, this PR adds this functionality.
https://user-images.githubusercontent.com/57798333/116010627-0ba94280-a618-11eb-8f1a-101b57000576.mov
> feat: add import of store state json to devtools middleware

- readme.md
- src/middleware.ts
- src/shallow.ts
- src/vanilla.ts
- tests/basic.test.tsx
Currently, `type State` in `zustand` forces all users to add an index signature to their state interfaces.
```ts
// We have to add 'extends Record<string, any>'
// which adds an index signature that we do not really want
export interface JediStore extends Record<string, any> {
jediName: string
jediPower: number
}
export const useChartComposerDataStore = create<JediStore>(...)
```
With this fix the index signature is no longer mandatory.
> fix: remove mandatory index signature

- readme.md
- src/middleware.ts
Bugfix for TypeScript.
Currently `combine` function accepts two states and merges them using `Object.assign` , but the type is `PrimaryState & SecondaryState` . The Intersection Type ( `&` ) merges deeply unlike shallow merge using `Object.assign` and Spread Operators `...` .
I added `Combine` type, which merges two generic types shallowly like the following, and use it for the return type of `combine` .
```ts
type A = {
foo: string;
bar: {
child1: string;
child2: number;
};
};
type B = {
baz: number;
bar: {
child3: boolean;
};
};
type C = Combine<A, B>;
// {
//    foo: string;
//    baz: number;
//    bar: {
//      child3: boolean;
//    };
// };
// The above is equal to `{ ...a, ...b }` and `Object.assign({}, a, b)`
```
The current version doesn't match types and actual behaviors like …
> Fix a return value type of `combine`

- readme.md
- src/middleware.ts
Thanks for zustand!
I've added a details section that explains how to use custom storage engines for the `persist` middleware. The type `StateStorage` is exposed for TS users of zustand. 
Relates to discussion on issue #404 on how to use `IndexedDB` as the storage engine. 
Please let me know any changes and I would be happy to address them.
> Expose `StateStorage` type and update persist midlware documentation

- tests/basic.test.tsx
- tests/persistAsync.test.tsx
Notes:
- used `@ts-ignore` twice, makes sense that way IMO ([here](https://github.com/pmndrs/zustand/pull/417/files#diff-c21e24854115b390eccde717da83f91feb2d5927a76c1485e5f0fdd0135c2afaR299) and [here](https://github.com/pmndrs/zustand/pull/417/files#diff-c21e24854115b390eccde717da83f91feb2d5927a76c1485e5f0fdd0135c2afaR343)
- There are 2 TS errors right now which I'm not sure how to resolve as the test seems to violate the type definitions. Remove the test? Ignore the error? One in line 222 and one in 259
- The remaining `any` in the file I couldn't easily remove (L387:404), and the way the test was written looked a bit strange. Should the test really be the way it is, with `getState2()` calling `getState()`which is defined in the outer scope?
> Remove usage of `any` from tests

- tests/persistAsync.test.tsx
- tests/persistSync.test.tsx
Using `jest.fn()` not only is more concise but more importantly is less prone to be used incorrectly.
As an example, `expect()` calls within the `onRehydrateStorage` callbacks would not make a test fail at all.
Also in `persistAsync.test.tsx` add some checks verifying that `onRehydrateStorage` was not called with an error. (In `persistSync.test.tsx` those checks had been added previously.)
> Use jest.fn() to test callbacks

- tests/subscribe.test.tsx
This commit also fixes the test  `should be called if new state identity is different` which was broken by 4632b74 (and unfortunately didn't fail).
> Change tests for subscribe() to use jest.fn()

- src/middleware.ts
From PR#397, we changed the type of `PartialState`, so when combining `devtools` with `immer`, we have type error.
**Before**
```ts
export type PartialState<T extends State, K extends keyof T = keyof T> =
| (Pick<T, K> | T)
| ((state: T) => Pick<T, K> | T)
```
**Now**
```ts
export type PartialState<
T extends State,
K1 extends keyof T = keyof T,
K2 extends keyof T = K1,
K3 extends keyof T = K2,
K4 extends keyof T = K3
> =
| (Pick<T, K1> | Pick<T, K2> | Pick<T, K3> | Pick<T, K4> | T)
| ((state: T) => Pick<T, K1> | Pick<T, K2> | Pick<T, K3> | Pick<T, K4> | T)
```
If we define `immer` like `README`
```ts
const immer = <T extends State>(
config: StateCreator<T, (fn: (draft: Draft<T>) => void) => void>
): StateCreator<T> => (set, get, api) =>
config((fn) => set(produce<T>(fn)), get, api)
``` …
> export NamedSet type for combining with immer

- src/middleware.ts
- tests/persistAsync.test.tsx
When the state loaded from the storage would need to be migrated but the persist configuration doesn't contain a migrate function `onRehydrateStorage` would be called with the initial state. Now it is called with the state loaded from the storage, which in this case is assumed to be undefined.
> Fix argument of onRehydrateStorage for missing migrate function

- package.json
- src/middleware.ts
- tests/middlewareTypes.test.tsx
- yarn.lock
According to #434, we are having issue with typescript when combining devtool with persist middleware.
The main issue is because NamedSet and SetState are not compatible, so I think we can temporary make them compatible.
I already added some codes to test the type for middleware use case only. And also add `immer` as `devDependency` for testing (not sure this is a way, I will remove if it's not suitable).
> make type NamedSet compatible with type SetState

- tests/persistAsync.test.tsx
The test started to fail on master because #436 and #437 were developed in parallel and #436 was merged before #437.
This situation is interesting for 2 reasons:
1. It shows that #436 did add a test that was missing before: It tests an async storage without an initial value.
2. This test shows that the argument of `onRehydrateStorage` not only differ when the migrate function is missing (as was assumed in #437) but when the store is empty. The reason for the difference is that `get()` (see [here](https://github.com/pmndrs/zustand/pull/437/files#diff-0626369278c89781505d2c04865ecce1302e979271bcfb471e029c19addc13a0L360)) returns `undefined` when the storage is synchronous but returns the _default store value_ when asynchronous. The reason for the difference is that in sync mode the default …
> Fix failing test in persistAsync.test.tsx

- readme.md
Until now the immer proxy sample code supports only functions. But the original `set` of zustand also allows to provide an object. The updated immer middleware sample in this pr allows an object too. With this change the immer middleware is fully compatible with the `set` function of zustand.
> Compatible set function of immer middleware proxy

- babel.config.js
#419 had an issue. we still have one generator for backward compatibility.
This PR prevents using regenerator.
The impact is only on IE11 users who still use v2 API.
> fix: cjs build, no regenerator

- src/middleware.ts
- tests/persistAsync.test.tsx
- tests/persistSync.test.tsx
Follow up of #459 
This pr adds a new `merge` option for `persist` which can be used to do custom hydration merges.
> feat(persist): add a merge function option

- src/context.ts
Recent depracation of `initialStore` prop in `Provider` component causes broken declaration files to be generated. This causes TS compilation error when not using `skipLibCheck: true`.
```
node_modules/zustand/context.d.ts:5:18 - error TS2339: Property 'initialStore' does not exist
on type '{ createStore: () => UseStore<TState>; children: ReactNode; }'.
5     Provider: ({ initialStore, createStore, children, }: {
~~~~~~~~~~~~
```
You can see this error reported in the `context.d.ts` file after building the package.
```ts
// master version
import { ReactNode } from 'react';
import { UseStore } from 'zustand';
import { EqualityChecker, State, StateSelector } from './vanilla';
declare function createContext<TState extends State>(): {
Provider: ({ initialStore, createStore, children, }: { …
```
> Revert Provider initialStore types

- package.json
We had some discussions in https://github.com/pmndrs/valtio/pull/169.
Zustand doesn't have any module states, so it's just safe to add "import".
I hope this fixes #334. @wolframkriesing would you like to confirm?
> fix: package.json exports to have import

- readme.md
The docs example for immer could embed the immer code in the common 'action' style setter as in the other examples. This might give a better example of the common usage of immer in zustand. Otherwise, it encourages putting the setter code in the component
> better immer help

- src/context.ts
The changes from #484 cause an error when building declaration files from code using the `createContext` API. This was an oversight and the interface has to be exported or the declaration files cannot be emitted properly. I suppose TypeScript is not able to infer an interface that only contains call signatures with it not being exported.
```
error TS4023: Exported variable 'useStore'
has or is using name 'UseStoreData' from external module ".../node_modules/zustand/context" but cannot be named.
```
Exporting the interface fixes this error (tested it locally). I'll also change the name of the interface if needed.
> fix(context): Export UseContextStore interface

- readme.md
immer middleware with TypeScript example was missing the Draft wrapper type
> fix(readme): ts example of immer middleware

- .codesandbox/ci.json
- .size-snapshot.json
- package.json
- rollup.config.js
- tsconfig.json
- Modify Rollup to output to a single folder
- Modify rollup typescript config
- Rename exports to point to `.mjs` in exports
- Added nextjs to the sandbox generators
> Package all files into a single dist folder

- tests/basic.test.tsx
- tests/context.test.tsx
Let's fix `delete initialState.value` which wasn't very nice.
> refactor(tests): cleaner tests

- readme.md
My team has just had a little discussion about this. I thought it would be useful to get this added to the docs, if I've understood your code correctly.
> docs: Clarify that listeners added with `subscribe` are called synchronously

- readme.md
- src/middleware.ts
- src/vanilla.ts
- tests/context.test.tsx
- tests/middlewareTypes.test.tsx
- tests/subscribe.test.tsx
deprecating the core subscribeWithSelector feature.
close #475 
close #555
> feat(middleware): subscribeWithSelector middleware

- package.json
- src/middleware.ts
- tests/context.test.tsx
- tests/middlewareTypes.test.tsx
As discussed in #616, I reverted some typing in #601, which was tricky and doesn't help to infer types for everything. This exports custom store types from middleware, so that users can manually type with middleware. Also added more tests for middleware typing.
> fix(middleware): simplify middleware types and allow explicit typing

- src/index.ts
https://twitter.com/dai_shi/status/1454938054276239364
Well, it's basically adding one line.
> fix(core): useDebugValue in useStore

- src/middleware.ts
- tests/middlewareTypes.test.tsx
- tests/persistAsync.test.tsx
- tests/persistSync.test.tsx
> feat(middleware): add persist api

- src/context.ts
- src/middleware.ts
- src/vanilla.ts
I know this is mostly about preference, but I feel a little bad about mixing two styles for maintainability.
There are some differences between interface and type alias, like overloading, index signature and maybe others.
However, in the current code, mostly type alias is used and only some cases use interface. Hopefully making it consistent makes sense. (In this PR, to type alias.)
If this causes a real problem rather than styling preference, we can revisit. (I can think of one case, module augmentation, but wonder if anyone does it, and if it's the case, we should prefer "export function" too.)
> refactor(types): prefer type alias

- src/middleware.ts
- tests/middlewareTypes.test.tsx
> feat(middleware): devtools to patch api.setState with namedSet and fix middleware types

- src/index.ts
- src/vanilla.ts
- tests/middlewareTypes.test.tsx
close #638 
It generally improves the compatibility for pre v3.6.
> fix(types): fix core types to better handle middleware types

- src/middleware.ts
- tests/persistAsync.test.tsx
- tests/persistSync.test.tsx
I noticed in #644 that I kind of misnamed `useStore.persist.onHydrate` :grimacing: 
By the name `onHydrate` we would most likely expect the callback to be called when hydration starts, while in reality it's called when hydration is finished.
I fixed this by actually calling `onHydrate`'s callback when hydration starts, and adding a new `onFinishHydration` method to the persist api.
This pr also adds a new `useStore.persist.useHydration()` hook to make it easier to (mainly?) know if hydration is finished.
> feat(middleware): add onFinishHydration to persist api

- readme.md
> Remove devtools prefixing from readme

- readme.md
Newcomers to zustand may be confused why devtools doesn't show action types by default (I was!), so I've added  a note to the readme following [this comment from @devanshj ](https://github.com/pmndrs/zustand/issues/705#issuecomment-992976936)
> docs: add note about using set() third param for logging

- src/middleware/devtools.ts
- tests/devtools.test.tsx
- When setting the state from the devtools we used to temporary turn off recording and then we turn it back. But turning it back isn't correct, what if it was already turned off? Hence we now restore instead of turning it on.
- If the action received isn't a string then instead of parsing it we log a "Unsupported action format"
- We're now overwriting dispatch before subscribing to the devtools just in case of hypothetical sync (eg while testing) dispatching of actions from the devtools
> devtools: minor fixes for pause recording feature

- src/middleware/devtools.ts
- tests/devtools.test.tsx
close #723
When I reviewed #675, I thought it's clean without try-catch.
Later, an issue is reported and we fix it with #693, but that wasn't enough.
This is to revert to pre #675, with try-catch.
> fix(middleware): revert devtools extension connector with try-catch

- src/middleware/devtools.ts
From #715:
> - `devtools({}, name)` to `devtools({}, { name }`. Ability to pass the name directly is a rather unnecessary feature, more over expecting an object is consistent with `persist`. Good part is the documentation doesn't mention that you can directly pass the name so hopefully many users would not be using it.
> fix(middleware/devtools): deprecate passing name directly instead of an object

- examples/src/App.js
- examples/src/components/Backdrop.js
- examples/src/components/CodePreview.js
- examples/src/components/CopyButton.js
- examples/src/components/Details.js
- examples/src/components/Effects.js
- examples/src/components/Scene.js
Based on my comment here: https://github.com/pmndrs/zustand/issues/747#issuecomment-1010670457
This simply pulls much of the design code out into separate files, so that `App.js` has a clearer focus on declaring the store and implementing the counter.
> chore(examples): Refactor demo code to reduce distraction from Zustand usage

- src/middleware/devtools.ts
> fix(devtools): don't show jsdoc deprecation warning when no options are passed

- src/middleware/devtools.ts
- src/middleware/persist.ts
- src/middleware/subscribeWithSelector.ts
Match
https://github.com/pmndrs/zustand/blob/0ba3c240078cf61792a4b13ff11d774ecca70a0a/src/vanilla.ts#L50-L52
to make subscribeWithSelector more useful with custom states.
Ran into this when trying to use subscribeWithSelector with
custom middleware that uses immer's WritableDraft on SetState
> match vanilla StateCreator type in middleware/subscribeWithSelector

- src/context.ts
- tests/context.test.tsx
> fix(context): revert removing overloads in `UseContextStore`

- src/middleware/persist.ts
- tests/persistAsync.test.tsx
When using persist middleware, it's possible to mutate the store state in an useEffect callback before hydration creates `stateFromStorage`. It should merge the storage value with the latest store state instead of the config result since it can be out of date.
To reproduce:
1. create a storage whose getItem returns the value after a 2sec timeout. The storage is responsible for persisting a partial state. (property a)
2. add a useEffect to update the state right after render. It adds another property to the store. (property b)
Expected: When the storage value is fetched, it merges storage value with the latest store value.
Actual: When the storage value is fetched, it merges storage value with the initial store value.
Error demo: https://codesandbox.io/s/react-forked-oo16v5?file=/src/App.js …
> fix(middleware/persist): Merge storage value with the latest store state

- package.json
- rollup.config.js
- yarn.lock
In v4, we will allow `useStore` + vanilla store usage, it's better to avoid code duplication.
This is how we do in valtio.
(Just noticed, UMD is not supported by use-sync-external-store. Same for valtio.)
> fix(build): separate vanilla build

- docs/typescript.md
Fixes errors:
```
Generic type 'Write' requires 2 type argument(s).
Parsing error: '>' expected.
'>' expected.
Cannot find name 'A'.
```
> Docs: Fix TypeScript docs for Middleware that changes the store type

- src/middleware/devtools.ts
- tests/devtools.test.tsx
This is something we forgot in #892.
Also did some refactor to remove our own options in DevtoolsOptions.
> breaking(middleware/devtools): remove checking old string option

- src/react.ts
There was a `TODO` in react.ts.
I originally thought this requires StoreMutator, but it doesn't actually mutate. So, it's rather simple?
> fix(types): avoid any in react.ts

- docs/typescript.md
Fixes typo in Typescript Docs for authoring middlewares
> docs(typescript): fix typo in middleware without mutations

- docs/typescript.md
> docs(typescript): Add a note to not use curried version when using state-creating middlewares

- docs/typescript.md
- readme.md
Fix some code typo in `typestript.md` , to make them runnable on copy-paste.
And fixed some spelling issues in README
> chore(docs): fix typo in docs & code examples

- readme.md
Fixed typo "seperate" to "separate".
> docs: typo in readme.md

- examples/package.json
- examples/yarn.lock
Saw a lot of warnings in the console on the demo site ([https://zustand-demo.pmnd.rs/](https://zustand-demo.pmnd.rs/)),
the reason is because the incorrect dependency of `three`,
downgrade `three` to version `0.120.1` the warnings no longer exist.
Related issue: pmndrs/postprocessing#246
> fix(deps)(example): incorrect peer dependency version of three

- examples/config-overrides.js
- examples/package.json
- examples/src/App.js
- examples/src/components/Backdrop.js
- examples/src/components/CodePreview.js
- examples/src/components/CopyButton.js
- examples/src/components/Details.js
- examples/src/components/Effects.js
- examples/src/components/Fireflies.js
- examples/src/components/Scene.js
- examples/src/index.js
- examples/yarn.lock
Working on the example site, 
1. Update `react-scripts` and `react-app-rewired`.
2. Remove `customize-cra-react-refresh` because `react-refresh` is included in the newest version of `react-scripts`.
3. Resolve minor eslint warning.
4. Finally can remove all the `import React from 'react'` statement.
Tested `yarn build && serve -s build` everything seems to be working well.
> build(deps)(example): update build script packages

- docs/auto-generating-selectors.md
Like you said in #1008 you want to migrate the docs from Github's wiki to the docs folder as markdown files and I'd like to help! This one is for [Auto generating selectors](https://github.com/pmndrs/zustand/wiki/Auto-Generating-Selectors).
I will work on all the pages in my fork and open PRs if that's fine?
A few things:
-  I removed some semicolons from the wiki page in the last commit (aabaaad1b92a7b33b0aa07803856b2fb42bbdfc3). These semicolons are added back in by prettier for some reason
- The prettier and eslint scripts do not run on windows for me, but they ran fine in a ubuntu wsl.
- I did not test a lot of the code provided in the examples. Should I do so or is it save to assume that it's still valid?
Looking forward to your suggestions
> Migrate docs from wiki: auto generating selectors

- docs/typescript.md
There is a problem in the `combine` code example in `typescript.md`, and a ` )` symbol is missing at the end.
---
This is an online example: ↓
> https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAYygUwIY2XAZlCI4BEAXgK4DOMqAdgCYEBQokscA3ongEbBWYC+2XPmLlKtAPQhgNGgBtkAd1QoG9BBCoU45ZAGUY0TAF5EKdMgAU6kN14X2nNFDIAuOAAY4fADRwLZZBgASjgjAD4-Vno4OB4kNAC3C04ATzcqEhtkKBDwuACYC39KDFyI+zhHZVd8kuQAOirnOABqSpSvIKDvej4uoA
> docs(typescript): supplement the missing `)` symbol in the `combine` code example

- readme.md
Located at _`Reading/writing state and reacting to changes outside of components`_
Supplement the ending symbol of the `Component` function 😄
---
> docs(readme): symbol supplement in code example

- src/vanilla.ts
Fixes some upcoming build breaks in TypeScript 4.8. I'm not entirely sure the true root cause, but it looks like we're computing the correct variance of more of these types, leading to a (correct) error issued in covariant use sites like this:
```ts
export function useStore<TState extends State, StateSlice>(
api: WithReact<StoreApi<TState>>, // <- correctly marked as constraint violation
```
> Mark more methods bivariant

- docs/persisting-store-data.md
- src/middleware/persist.ts
- tests/persistSync.test.tsx
This pr can be relationated to:
- Expose getOptions method on persist api
- Update Documentation with examples of storage event listener
- Add test for the new method
- options were given so that this [issue](https://github.com/pmndrs/zustand/issues/714) can be solved
> feature(persist): add method getOptions on persist api and update documentation

- src/vanilla.ts
I've done the initial deprecation work, the following work is up for grabs...
- Migrate the whole codebase to not use deprecated types
- Consider reordering exports in a way the deprecated types are exported at the bottom, it might affect the user's autocomplete and show more useful types first.
> feat(types): minimize types by deprecating them

- .eslintrc.json
- src/context.ts
- src/middleware/devtools.ts
- src/middleware/persist.ts
- src/middleware/redux.ts
- src/middleware/subscribeWithSelector.ts
- src/react.ts
- src/vanilla.ts
- tests/basic.test.tsx
- tests/context.test.tsx
- tests/middlewareTypes.test.tsx
- tests/types.test.tsx
This mostly reverts #1012. 
`@typescript-eslint/consistent-type-definitions` rule doesn't work for library code.
So, our new ground rule is:
- prefer interface for public api (always with `export`)
- otherwise, prefer type alias
close #1100 
close #1103 
close #1113 
---
jotai and valtio should follow this too.
> fix(types): use TS interfaces only for public api

- src/shallow.ts
- tests/shallow.test.tsx
> fix(shallow): types with useStore

- tests/basic.test.tsx
- tests/middlewareTypes.test.tsx
- tests/types.test.tsx
> refactor(types): avoid using deprecated types in tests

- examples/src/components/CodePreview.js
This reduces 8.54kb of the bundle size for the example site.
Cannot use the new theme from `'prism-react-renderer/themes/okaidia'` although they have the same name `okaidia`, the style still looks different. Followed [the introduction](https://github.com/FormidableLabs/prism-react-renderer#faq) and used the old Prism css theme, removed unnecessary imports of "prismjs".
The output is as same as before
> perf(example): remove unnecessary imports of "prismjs"

- docs/auto-generating-selectors.md
- docs/event-handler-in-pre-react-18.md
- docs/flux-inspired-practice.md
- docs/persisting-store-data.md
- docs/typescript.md
- readme.md
- tests/basic.test.tsx
- tests/middlewareTypes.test.tsx
- tests/persistAsync.test.tsx
- tests/persistSync.test.tsx
- tests/shallow.test.tsx
- tests/types.test.tsx
```js
const useStore = create(...)
```
seems confusing IDEs.
We should prefer
```js
const useFooStore = create(...)
```
with "Foo" being anything meaningful or "Bound" as type says.
> fix(docs): useBoundStore instead of useStore

- examples/src/components/Scene.js
- examples/src/index.js
fix #1158
The custom canvas was implemented incorrectly, I forgot to extend the THREE namespaces, take the solution from below:
https://github.com/pmndrs/react-three-fiber/discussions/2402#discussioncomment-3270482
And also remove the unnecessary extend `extend({ PlaneBufferGeometry })` in `Scene.js` since the THREE namespaces are now fully registered.
> fix: live demo failure

- docs/typescript.md
Not sure if `useBoundStore` had some special meaning in other places, but there were incorrect references to it in the `combine` comment that didn't match the example. (I just replaced it with `useBearStore` everywhere assuming it was a typo.)
> fix typo in typescript.md

- tests/basic.test.tsx
Fixed console error about React 17 -> 18 in `basic.test.tsx`
> chore(tests): remove imperfectly working test added in #276

- readme.md
Persist middleware requires the name option to keep storage unique.
See https://github.com/pmndrs/zustand/blob/main/docs/persisting-store-data.md#name
This change adds the 'name' option to the Typescript Usage example to update it.
Additionally, the persist example already has this required option.
> Fix Persist in TypeScript Usage on readme

- readme.md
- src/middleware/devtools.ts
- src/middleware/immer.ts
- tests/devtools.test.tsx
- tests/middlewareTypes.test.tsx
- adjusted setState's `actionType` typing to contain `payload` (devtools middleware)
- added appropriate info to documentation
- added appropriate test (+ little tests refactor)
> fix(types)(middleware/devtools): fix action type in devtools's setState

- src/middleware/devtools.ts
- src/middleware/redux.ts
In #1144, I made some types loosen, which includes not only `State` but also `Action` in the redux middleware. @devanshj pointed out that it can cause misusage with the combination of `redux` and `devtools` middleware.
So, I'm convinced to revert the `Action` part of the change.
> fix(middleware): revert types of redux middleware

- src/context.ts
- src/middleware/combine.ts
- src/middleware/devtools.ts
- src/middleware/immer.ts
- src/middleware/persist.ts
- src/middleware/redux.ts
- src/middleware/subscribeWithSelector.ts
- src/react.ts
Since we have downlevel-dts, we can use `import type` statement.
This is not a big deal, but it makes the code consistent with that in [jotai](https://github.com/pmndrs/jotai) and [valtio](https://github.com/pmndrs/valtio).
> refactor(types): prefer using import type

- readme.md
Fixes some broken links on readme, mostly files that were moved to a subfolder of ./docs.
> docs: fix broken links on readme

- docs/guides/auto-generating-selectors.md
- docs/guides/event-handler-in-pre-react-18.md
- docs/guides/flux-inspired-practice.md
- docs/guides/immutable-state-and-merging.md
- docs/guides/testing.mdx
Fixes #.
- [Issue 1120](https://github.com/pmndrs/zustand/issues/1220).
Reviewed the following for grammatical errors and minor style changes:
- testing.mdx
- auto-integrating-selectors.md
- event-handler-in-pre-react-18.md
- flux-inspired-practice.md
- immutable-state-and-merging.md
In those five documents, I encountered two broken links. Both were in `flux-inspired-practice.md`. I was able to replace one with the proper code link. However, I couldn't for the second, as I couldn't find the proper link. You can see it right before the last code block in the file, with the text `[this example](https://codesandbox.io/s/amazing-kepler-swxol)`
> Issue 1120 docs

- docs/guides/how-to-reset-state.md
Fixes #1008 
Move how to reset state to ./docs
> fix(docs): Add how to reset state to docs/guides section

- docs/getting-started/comparison.md
Fixes #1008 
- Move difference between zustand and valtio to ./docs
- Updating zustand vs redux
- Adding other comparisons
> fix(docs): comparison

- docs/guides/connect-to-state-with-url-hash.md
- docs/integrations/persisting-store-data.md
Fixes #1254
Reviewed the following documentation:
- Location of added content
- typescript
- custom storage is connected Hash url usage
> fix(docs): Issue 1254 guides 

- readme.md
[Fixes](https://github.com/pmndrs/zustand/issues/1300)
Remove dead link as mentioned:
- https://github.com/pmndrs/zustand/issues/1300
- https://github.com/pmndrs/zustand/pull/1231#issuecomment-1229575111
- https://github.com/pmndrs/zustand/issues/1216#issuecomment-1236031336
> docs: remove dead link from readme

- docs/getting-started/comparison.md
Fixes #.
Typo fix: Jotai is used instead of Recoil in the Recoil section
> fix(docs): type replace Jotai with Recoil

- docs/recipes/recipes.mdx
- readme.md
Document the `enabled` option for devtools middleware.
> docs: expose `enabled` devtools options in the documentation

- docs/guides/slices-pattern.md
- docs/guides/typescript.md
#1253
As per [comment](https://github.com/pmndrs/zustand/issues/1253#issuecomment-1235321069):
> docs: added docs file for slices pattern

- src/context.ts
Fixes #.
When the store is created with persist middleware, property `storeApi.persist` is missing, which does not match its type.
The internal function `useBoundStore` should be named as `useContextStore`, because the store API is not assigned to it.
> fix(context): store property missing from `useStoreApi`

- src/vanilla.ts
- tests/basic.test.tsx
> fix: should use Object.is to compare two value

- docs/guides/flux-inspired-practice.md
- readme.md
Link readme and flux guide to the dedicated slices pattern guide instead of the slices pattern section from typescript guide, now that #1344 is in.
Readme and flux guide were the only documents linking to the typescript section, so all links that needed updating and updated with this PR.
> Update slices pattern links in readme and flux guide

- src/vanilla.ts
- tests/types.test.tsx
Fixes #1368. Implements the option 2 mentioned in the issue.
> fix(types): assume `getState` and `setState` will always exist on the store

- docs/guides/typescript.md
- src/middleware/devtools.ts
- src/middleware/immer.ts
- src/middleware/persist.ts
- src/middleware/redux.ts
- src/middleware/subscribeWithSelector.ts
- src/vanilla.ts
- tests/types.test.tsx
I originally had the phantom type because I assumed it would be required. I'm still a little skeptic about this change but just want to expermiment and see the CI results hence opening the PR.
This PR's branch is based on #1372's branch. Note that this does not require the change in #1372, but has it as base because if we're going with #1371 this PR would probably be much less useful.
> fix(types): fix `StateCreator` subtyping

- docs/recipes/recipes.mdx
Examples used from README and are now copy/pasteable without throwing errors in sandbox
#1378 @chrisk-7777 @dai-shi 
Fixes #.
> Update recipes.mdx: Using subscribe with selector

- docs/integrations/persisting-store-data.md
Issue not created, but the problem can be replicated by visiting https://docs.pmnd.rs/zustand/integrations/persisting-store-data, then clicking on the "Hydration and asynchronous storages" link in the second paragraph.
Make section hash hrefs all lowercase so in-page links work properly on Persisting Store page. The problem likely stemmed from porting Github's implementation of markdown, which is capitalization agnostic about URL hashes, to the new docs framework.
- Remove a "see below for more details" link that is linked to the next section.
- Add additional context to a different "see below" statement.
> Persisting store doc href hash fixes and tweaks

- docs/recipes/recipes.mdx
In the 'Persist middleware' example, there is no `fish` property; it should be `fishes`.
> docs/recipes: persist example should reference 'fishes', not 'fish'

- docs/integrations/updating-draft-states.md
> fix(docs): fix to -> do typo

- docs/guides/auto-generating-selectors.md
> fix(docs): Fix 'State' declaration position

- src/middleware/devtools.ts
Fixes #1427.
Remove optional catch binding syntax usage in devtools.ts, since it's the only one place it has been used and it is not transpilled correctly to backward compatible syntax.
> fix(middleware/devtools): do not use optional catch binding syntax

- src/shallow.ts
- tests/shallow.test.tsx
Zustand allows storing Maps and Sets, however, the `shallow` comparator returns incorrect comparison results for these type.
This PR adds support for shallow comparison of ES6 `Map` and `Set`
> feat(shallow): Add support of Maps and Sets to shallow comparator

- src/vanilla.ts
Add binding of createStoreImpl methods types to StoreApi without hardcoding.
In case of changing something in StoreApi type we dont have to change it again inside createStoreImpl
Fixes #.
Removing arrow function types reduces number of arrows, and makes it easier to read.
Makes it easier to read and reason about where the type comes from and belongs to.
> refactor(vanilla/types): replace hardcoded types with StoreApi type

- rollup.config.js
Patches the base index file to export the default as classic node cjs module
Fixes #559
> Fix: Programmatic `module.exports` addition for named and default exports in CJS

- docs/guides/updating-state.md
- docs/integrations/immer-middleware.md
Relates to #1220.
- Fixed case in naming of Immer,
- Checked if the code snippets are up-to-date,
- Ensure common style of directly addressing the reader ("we" -> "you").
> Revise the Immer middleware page

- docs/integrations/persisting-store-data.md
Relates to #1220.
- add cross-links
- add line breaks for easier Markdown reading
- unify Persist middleware spelling
- change fishes to bears, because the plural of fish is fish,
and it would be less readable
- make sentences more concise
> Revise Persisting store data doc page

- rollup.config.js
Fixes #1475
Patches the issue where exports.default might not get translated because of the `_esModule` property
Tested with 
- Parcel v2 
- Webpack (Current CRA) 
- All CSB Additions from the CI
> fix(build): disable esModule and re-export for nodejs

- readme.md
Fixes #.
This PR fixes some minor grammar mistakes and typos.
> docs: Fixed minor grammar & typo issues

- docs/migrations/migrating-to-v4.md
- docs/migrations/v4-migration.md
Relates to #1220.
- Rename "v4 migrations" to "Migrating to v4", as it is more likely to be search by users.
- Restructure the documentation:
- Drop the "Change" and "Migration" third-level headers,
as they were cluttering the outline[^1],
and produced incorrect section links
(`#change` always linked to the first occurence).
Use bolded text without it being header instead.
- Drop the "(from `zustand`)" header add-ons.
- The final outline is much cleaner now[^2].
- Instead of header add-ons,
e.g., "(from `zustand` and `zustand/vanilla`)"[^3],
add "Applicable imports" subsection[^4].
- Split the paragraphs with if/else instructions,
so that they are easier to understand.
- Rephrase paragraphs, so they are more grammatically correct
and easier to understand.
[^1]: Old outline: <img …
> Revise v4 migrations doc page

- docs/integrations/persisting-store-data.md
This replaces `getStorage` with `storage`.
This PR raises two questions:
- Should we write documentation on how to migrate from the `getStorage` API to the `storage` API?
- Should we version the middleware separately from the zustand core?
> Update persist documentation for `storage`

- docs/getting-started/comparison.md
- docs/getting-started/introduction.mdx
- docs/guides/connect-to-state-with-url-hash.md
- docs/guides/how-to-reset-state.md
- docs/guides/immutable-state-and-merging.md
- docs/guides/maps-and-sets-usage.md
- docs/guides/slices-pattern.md
- docs/guides/testing.mdx
- docs/guides/typescript.md
- docs/integrations/immer-middleware.md
- docs/integrations/persisting-store-data.md
- docs/recipes/recipes.mdx
- readme.md
- src/index.ts
- src/react.ts
- src/shallow.ts
- src/vanilla.ts
- tests/basic.test.tsx
- tests/context.test.tsx
- tests/devtools.test.tsx
- tests/middlewareTypes.test.tsx
- tests/persistAsync.test.tsx
- tests/persistSync.test.tsx
- tests/shallow.test.tsx
- tests/subscribe.test.tsx
- tests/types.test.tsx
> feat: deprecate default export

- src/middleware/persist.ts
- tests/persistAsync.test.tsx
- tests/persistSync.test.tsx
Fixes #1517.
In #1463, I hoped to avoid `toThenable()` whose implementation is complicated, and used `Promise.resolve()` instead. I wasn't aware this is a regression because it didn't migrate the tests.
This PR fixes the tests, and use `toThenable`.
> fix(middleware/persist): hydrate in sync (new impl with storage option)

- src/middleware/persist.ts
- src/react.ts
- src/shallow.ts
- src/vanilla.ts
While writing 4.3.0 release note, I noticed deprecation messages will be shown in production. Let's make them dev only.
> chore: show deprecated message only in DEV

- docs/previous-versions/zustand-v3-create-context.md
https://github.com/pmndrs/zustand/pull/1403#discussion_r1065627397
> docs: add migration example in v3 create context

- docs/integrations/third-party-libraries.md
Add [zustand-di](https://github.com/charkour/zustand-di) third-party package in anticipation of `createContext` from `zustand/context` being removed in v5 of zustand.
> Add zustand-di to third-party docs

- docs/getting-started/comparison.md
Add missing close parenthesis on Zustand example
> fix(docs): Invalid example in comparison docs

- src/middleware/persist.ts
Went ahead with the PR, skipped the issue.
The storage must be operating with the persisted state type, which by default matches the state type. Otherwise it's not possible to introduce serialization/deserialization logic.
An example of how this would be useful:
```typescript
export function createSerdeStorage<State, RawState>(
serialize: (state: State) => RawState,
deserialize: (rawState: RawState) => State,
getStorage: () => PersistStorage<RawState>
): PersistStorage<State> {
const storage = getStorage();
return {
getItem: async (name) => {
const data = await storage.getItem(name);
if (data === null) return null;
return {
...data,
state: deserialize(data.state),
};
},
setItem: (name, value) =>
storage.setItem(name, { ...value, state: serialize(value.state) }),
removeItem: …
```
> fix(middleware/persist): Fix the storage type

- docs/guides/testing.mdx
(None)
Update testing doc because default exports is deprecated in v.4.3.0.
Mocking zustand(using v4.3.2) according to the TypeScript guide results in the following error.
So I used aliases and named export.
The test is working correctly in my environment.
> docs: update testing

- docs/guides/typescript.md
Discussion: https://github.com/pmndrs/zustand/discussions/1564
Fixes #.
Providing documentation for accessing and using vanilla stores and bound stores using typescript
> fix(docs/typescript): add typing usage with custom store hooks

- docs/guides/typescript.md
#1565 
Fixes #.
Comment on incorrect initial state usage in example
> fix(docs/typescript): use correct initial state in test example

- docs/guides/typescript.md
#1565 
Fixes #.
Providing an example of using middlewares with vanilla stores using typescript
> fix(docs/typescript): provide example how to use middlewares with #1565

- docs/guides/typescript.md
Supercedes #1565.
The recipe added in #1565 is unnecessarily wordy beyond measure. That's not to blame the author (or the maintainers) as they might not be aware of how the TypeScript guide is supposed to be. I just want to clarify my intention of the TypeScript guide as the original author: A succint to-the-point document that shows you how to deal with TypeScript, period. (This ignores the extra collapsed sections of course, which is precisely why they are collapsed.)
Which means it's not there to teach you how to use zustand patterns or anything. If you look at every recipe, it's literally just a snippet to show you the typings. So when the user comes to the "slices pattern" recipe for example, it is assumed they know what "slices pattern" already is, hence we don't teach slices …
> docs(typescript): clean up bounded `useStore` recipe

- CONTRIBUTING.md
https://github.com/pmndrs/zustand/discussions/1033#discussioncomment-3967766
Fixes #.
I made an initial version of a contributers guide.
This one is derived from the jotai `CONTRIBUTING.md` and the guide @chrisk-7777 made. I applied some small changes .
If this is not needed atm please feel free to discard this PR.
> fix(docs): add an initial version of a contributers guide

- .gitignore
Fixes #.
Removes redundant configuration items `coverage/` and `.idea` from the .gitignore file.
> chore: remove redundant configuration from .gitignore

- src/context.ts
- src/middleware/persist.ts
- src/react.ts
- src/shallow.ts
- src/vanilla.ts
Make deprecated messages copy consistent. Minor copy cleanup otherwise.
* Most importantly, add space after `from` (e.g. in `import { shallow } from'zustand/shallow'`).
> fix(log): deprecated messages copyedit for consistency

- docs/guides/testing.mdx
Inspired by #559
Default exports and imports are deprecated. The default import of `zustand` generates a deprecation warning on the console. The default export that was suggested previously would actually fail to compile. See the comments at the very bottom of #559 for further discussion.
This commit fixes the example in the documentation by introducing named exports & imports instead of default exports & imports.
> Fix Jest example's usage of default imports

- rollup.config.js
Fixes #1563 
Manually adds a set of `module.exports` for each file that needs a the CJS patch for exports. 
This is temporary and will be removed once zustand's API are all named instead of mixed.
> fix: add explicity export paths for cjs

- docs/guides/how-to-reset-state.md
By ading this example we can combine the real Slices pattern implementation (instead of multiple stores) with the resetAll method.
Hope this helps! 😄
Fixes #.
> fix(docs): Add Slices pattern example

- src/react.ts
- tests/types.test.tsx
`UseBoundStore` strictly enforces the shape of the `setState` function but does not rely on the shape of the `setState` function internally.
I want to define a middleware that makes the action in `devtools` required (to improve debugging store mutations in a large app). But if I make the third argument to `setState` required, the modified `setState` function is no longer compatible with the default `setState` function.
We get the following error message (edited for readability).
```
Types of property 'setState' are incompatible.
'<A extends string | { type: unknown; }>(
partial: T | Partial<T> | ((state: T) => T | Partial<T>), 
replace: boolean | undefined, 
action: A
) => void' 
is not assignable to 
'(partial: unknown, replace?: boolean | undefined) => void'.
```
Internally the `react` …
> fix(react, types): relax react types

- src/shallow.ts
Fix typo in `zustand/shallow` deprecation warning.
> fix: typo in shallow.ts

- docs/guides/connect-to-state-with-url-hash.md
The old demo in connect-to-state-with-url-hash.md is not available.
I have written a new demo.
> fix(doc): update state-with-url-hash demo

- docs/recipes/recipes.mdx
- https://github.com/pmndrs/zustand/discussions/971 (This PR was requested [here](https://github.com/pmndrs/zustand/discussions/971#discussioncomment-5388443))
- https://github.com/pmndrs/zustand/discussions/658
As per the discussions above, memoizing selectors does not improve performance significantly as of v4. Thus we should not recommend memoizing selectors.
Note that the same paragraph was removed from the README in https://github.com/pmndrs/zustand/pull/550 and this section may have been left behind as an oversight.
P. S. I wish the docs stated "selectors do not benefit significantly from memoization". I feel this doesn't belong in the Recipes page, though; perhaps a FAQ section is needed?
> Don't recommend memoizing selectors

- docs/integrations/persisting-store-data.md
- src/middleware/persist.ts
- tests/persistAsync.test.tsx
- tests/persistSync.test.tsx
Fixes #405
Add `skipHydration` boolean to persist options. This allows the developer to control when the persist middleware will hydate manually.
> feat(middleware/persist): add skip hydration option #405

- src/middleware/persist.ts
- tests/persistAsync.test.tsx
- tests/persistSync.test.tsx
Fixes #1688
See #1688 for a detailed description of the problem. This PR resolves the issue by ensuring `stateFromStorage` gets updated to the most recent value. I also added tests verifying this update pattern works for both synchronous and asynchronous storage APIs.
One note for reviewers: I added a comment describing how, in the asynchronous case, it's possible that the state passed to `postRehydrationCallback` is _not_ the most up-to-date state. This would occur if there was a state update between callbacks in the hydration promise chain. Please let me know if I should leave the comment as-is, make the change, or simply remove the comment.
> fix(middleware/persist): ensure `persist` does not drop updates in `onRehydrateStorage` when using a synchronous storage API

- src/middleware/persist.ts
- tests/persistAsync.test.tsx
- tests/persistSync.test.tsx
Fixes #1691
This PR ensures that the argument passed to `onRehydrateStorage` and `onHydrate` is defined during the first hydration of a store. Instead of passing the result of `get()`, which will always be `undefined` before the first hydration, `get() ?? configResult` is passed. I also added tests validating that `onRehydrateStorage` is always passed a defined value for `state`.
One caveat is that it's actually _not possible_ to add an `onHydrate` listener which will be invoked prior to first hydration. As such, I can't test this case, but I've documented it in the test I added.
An alternative solution would be to update the argument type signature of `onRehydrateStorage` and `onHydrate` and to `state?: S` instead of `state: S`, which reflects the potential for state to be `undefined`. …
> fix(middleware/persist): ensure argument for `onRehydrateStorage` and `onHydrate` is defined on first hydration

- examples/demo/src/components/Details.js
- examples/demo/src/styles.css
Fixes # https://github.com/pmndrs/zustand/discussions/1733
Add docs link on the demo page
Various breakpoints shown below. On smaller devices I've pushed it to the left under the logo. 
Note there is an existing issue where the Source and Credit link is pushed out of view on mobile devices. This doesn't address that (you can check prior to merging)
> demo: add docs link to the demo page

- docs/guides/typescript.md
> fix(docs): fixes ExtractState in TypeScript guide

- docs/getting-started/introduction.md
- docs/guides/testing.md
- src/middleware/devtools.ts
Fixes #905 
Update testing doc to support w/o middleware testing Zustand using Jest
> fix(docs): update testing doc

- docs/integrations/persisting-store-data.md
> docs: fix document error of persist with hydration

- docs/recipes/recipes.mdx
When looking at the [docs](https://docs.pmnd.rs/zustand/recipes/recipes#transient-updates-(for-frequent-state-changes))  for transient the params for subscribe accepts a second arg compared to the repo [Readme](https://github.com/pmndrs/zustand#transient-updates-for-often-occurring-state-changes).
- Removes second arg passed to `subscribe` in example
- Renamed `useStore` to `useScratchStore`
<hr>
> Update `Transient` in recipes to match Readme

- docs/guides/typescript.md
Fixes https://github.com/pmndrs/zustand/discussions/1564#discussioncomment-5735802
The overloaded return function from `createBoundedUseStore` had marked the first selector as optional. This was causing memoized selectors via `useCallback` to not be correctly typed. Removing the `?` solved the lost type inference.
> docs(typescript): fix bounded use store example

- docs/getting-started/comparison.md
Fixes 
Fix to show the code heading in the comparison of Zustand and Redux code.
> Add code heading in comparison with Zustand and Redux

- .github/workflows/test-multiple-builds.yml
> fix: workflow file syntax error

- src/middleware/persist.ts
- tests/persistAsync.test.tsx
- tests/persistSync.test.tsx
- tests/test-utils.ts
Fixes #618 
The related Issue is closed because a workaround exists. But I would love to see that possible without a workaround needed. Thats why I did this fix.
> feat(middleware/persist): improve createJSONStorage for Maps

- docs/recipes/recipes.mdx
Fixes #
The doc's description that you can name the store by `devtools(store, "MySore")`, but the second parameter in the source is a `devtoolsOptions` object rather than a string.
https://github.com/pmndrs/zustand/blob/0784028ed7591daf890c22ad4c065205cb35d2be/src/middleware/devtools.ts#L203
> docs(recipes): fix description of devtools store naming

- docs/integrations/persisting-store-data.md
Fixes #
Just docs 
I have spent the last 1h30m trying to find the solution for `Hydration failed because the initial UI does not match what was rendered on the server` and after digging a lot I found the solution. So i thought: Maybe this could be on official documentation! So I made it. It's just copy and paste but at least it will be easier for future folks trying to solve the same problem
> Add section for usage of persist middleware with NextJS

- docs/guides/connect-to-state-with-url-hash.md
I was trying to adapt [this URL hash example](https://docs.pmnd.rs/zustand/guides/connect-to-state-with-url-hash) to our codebase but it didn't worked. State didn't load on a refresh.
I figured out that it's because we `stringify` but not `parse` before loading the state.
Please take a look on the previous codesandbox and the new one in the diff.
> Fix saving state in URL hash example demo

- docs/guides/auto-generating-selectors.md
Small typo fix on the variable name for consistency with the other example a line above.
> docs: fixes typo on variable name

- docs/guides/connect-to-state-with-url-hash.md
I wrote some documentation extending the existing `Connect to state with URL hash` page to include code example for persisting state in localstorage and connecting state with URL parameters, and building shareable URL.
Thank you for a great project 🙏
> docs: persist and connect state with url

- docs/recipes/recipes.mdx
N/A
Replace the deprecated `getStorage` option with the new `storage` option with `createJSONStorage`. This matches the documentation changes made in #1463.
> Update Recipes persist example to match example in Persisting Store Data integration

- docs/integrations/persisting-store-data.md
The initialization type of `useState` is incorrect. hydrated needs to be of boolean type, whereas the original `useBoundStore.persist.hasHydrated` is a function. This will lead to errors, such as during the static build of frameworks like Next.js.
Fixes #
> docs(guides): fix "useHydration hook"

- readme.md
immer's "produce" function is being exported incorrectly, which can lead to potential confusion. For this you need to export using:
```ts
import { produce } from 'immer'
```
> docs(readme): fix import of "produce" function

- docs/recipes/recipes.mdx
Fixes documentation about shallow usage. 
Doc shows **import** from wrong package.
> [Documentation] Import shallow from right package

- docs/guides/connect-to-state-with-url-hash.md
- docs/guides/flux-inspired-practice.md
Addresses discussion 1863
Try to highlight the similarities, but also differences, from standard flux practices. 
**Note** I had to remove `<>` from the codesandbox link as it was causing issues when running the docs locally, see screenshot.
> docs: refine flux inspired docs to make pattern inspiration clearer

- readme.md
Modify example code that explain usage of Redux devtools.
> docs(readme): modify usage of Redux devtools

- docs/integrations/persisting-store-data.md
Typo fix in docs.
changed the following line:
- By default the store *with* be hydrated on initialization.
to
- By default the store *will* be hydrated on initialization.
> docs: fix typo 'with be' to 'will be'

- docs/guides/testing.md
- docs/guides/typescript.md
- readme.md
Had a look at the docs and made a few changes that I feel like make it easier to find stuff or read. For example I didn't immediately understand what the zustand mock enabled, or the renderCounter function being at the bottom of one of the codeblocks confused me for a little bit.
> improve docs readability

- docs/integrations/persisting-store-data.md
https://github.com/pmndrs/zustand/discussions/1955
This is a small fix for one of the examples in the docs (persist API).
The example:
Link: https://docs.pmnd.rs/zustand/integrations/persisting-store-data#how-do-i-use-it-with-map-and-set
Fixes TypeScript Error in this example and clarifies a certain type that isn't really any.
The type of `newValue` isn't exactly `StorageValue<any>` but `StorageValue<YourStateType>`.
This PR helps to clarify that and helps users have better types.
In addition, `str` in `getItem` could be `null` and that's why **this code won't compile**.
`zustand` is incredible and I do not wish to waste your time, I just thought this might help 💛
> Docs Example (Persist API): Avoid 'any', avoid "might be null" error and make example clearer

- package.json
- src/context.ts
- src/react.ts
- src/traditional.ts
- tests/basic.test.tsx
Fixes #1937
See #1937
Caveat 1: `createWithEqualityFn` has nothing to do with `subscribeWithSelector` middleware and we still need to specify equalityFn such as `shallow` for `subscribeWithSelector`.
> feat: deprecate equalityFn and add createWithEqualityFn

- docs/previous-versions/zustand-v3-create-context.md
Fixed a typo in `docs/previous-versions/zustand-v3-create-context.md`.
> docs: fix typo

- src/react.ts
https://github.com/pmndrs/zustand/discussions/1937#discussioncomment-6625047
It's an overlook in #1945, which breaks types with existing (deprecated) usage.
> fix(types): accept undefined equalityFn for the deprecated useStore

- src/react.ts
https://github.com/pmndrs/zustand/discussions/1937#discussioncomment-6639426
https://github.com/pmndrs/zustand/discussions/1937#discussioncomment-6643081
https://github.com/pmndrs/zustand/discussions/1937#discussioncomment-6646040
Follow-up #1945
Improve the warning message based on the feedback.
> fix: improve warning for deprecated equalityFn

- readme.md
https://github.com/pmndrs/zustand/discussions/1937#discussioncomment-6675672
Clarify to use `createWithEqualityFn` for `shallow`.
> fix(readme): description with createWithEqualityFn

- docs/guides/initialize-state-with-props.md
Passing an equalityFn to the useStore hook is deprecated. The documentation to initialize the store from props is recommending the approach. It was updated to recommend using useStoreWithEqualityFn instead.
BTW notice running prettier messed with a lot of files but didn't change the file I changed. I'm not pushing those other files formatting changes though.
> fix(docs): Do not recommend deprecated useStore + equalityFn on initialize with props docs

- docs/integrations/third-party-libraries.md
Fixes #
Added a third party library under integrations
[zustand-sync-tabs](https://www.npmjs.com/package/zustand-sync-tabs) — Zustand middleware to easily sync Zustand state between tabs / windows / iframes (SameOrigin)
> Add third party library

- docs/recipes/recipes.mdx
The `produce` function is a named export, not a default export:
https://immerjs.github.io/immer/produce
> fix(docs): Fix Immer import

- docs/guides/updating-state.md
Description:
This pull request adds import statements to the project's documentation to illustrate how to use the create and shallow functions from the zustand library.
Changes Made:
Added import statement for create from 'zustand'.
Added import statement for shallow from 'zustand/shallow'.
This pr addresses to issue #2024
The script is top before the changes- https://docs.pmnd.rs/zustand/guides/updating-state
Screenshots:
After my changes-
> fix: added 'create' and 'shallow' imports to docs

- docs/recipes/recipes.mdx
I've noticed that the usage without React in the recipes section of the documentation shows a deprecated use, which is different from the usage from the readme. This PR makes the recipes usage inline with the readme one.
> fix(docs): Update usage without React on recipes.mdx

- docs/getting-started/comparison.md
The bug --> currently in the comparison page ([https://docs.pmnd.rs/zustand/getting-started/comparison](url)) when you click on any **"State Model**" or **"Render Optimization"** internal link (whether its in the table of content or in the main content) it will always take you to the first link located in the page. 
This is because the hrefs generated from the pmndrs website are not unique and based on the element's content (which is the same in this case).
> docs: change titles in order to avoid duplicate hrefs

- src/traditional.ts
With the updates in v4.4.0 and the addition of the `createWithEqualityFn`, the types currently require `defaultEqualityFn` when the implementation itself [is optional](https://github.com/pmndrs/zustand/blob/deba6ed0d05b0dcb66c95177035ec8a061715745/src/traditional.ts#L94).
Thank you
> fix(traditional): make defaultEqualityFn optional in TS Types

- docs/guides/prevent-rerenders-with-use-shallow.md
- readme.md
- src/shallow.ts
- tests/shallow.test.tsx
Adds a `useShallow` hook to prevent unnecessary re-renders when a selector outputs the same value according to shallow equal. 
```tsx
import { create } from 'zustand'
import { useShallow } from 'zustand/shallow'
const useMyStore = create(() => ({ a: 1, b: 2, c: 3 }))
export const TestShallow = () => {
const output = useMyStore(useShallow(Object.keys))
return <div>{output.join(',')}</div>
}
```
See tests in `shallow.test.tsx` for more details.
---
- https://github.com/pmndrs/zustand/discussions/1937
- https://github.com/pmndrs/zustand/discussions/1937#discussioncomment-7118242
- https://github.com/pmndrs/zustand/discussions/1937#discussioncomment-6974554
> feat: add useShallow

- src/middleware/devtools.ts
Follow up #1991.
It infers to `any` instead of `unknown` if the type package isn't found.
> fix(types): mitigate devtools typing

- readme.md
Fixes https://github.com/pmndrs/zustand/discussions/1668#discussioncomment-7333194
- Passing the vanilla store is deprecated.
- Creating a slice is not for beginners.
> fix(readme): avoid deprecated/misleading usage

- rollup.config.js
Fixes #2127
When we added a new entry in zustand/shallow, our manual patch broke.
We don't have a test for this, but this patch will go away in v5 anyway.
> fix(build): patch entry points zustand/shallow for CJS

- docs/guides/testing.md
[#905](https://github.com/pmndrs/zustand/issues/905#issuecomment-1499264087)
Fix example jest/vitest mock on docs to handle currying
> fix(docs): support currying for testing mock

- docs/guides/typescript.md
- docs/integrations/immer-middleware.md
Fixes #2136
Moves the generic type from the `immer` middleware call to `create`. If you use the code as mentioned previously in the docs, you lose IDE introspection on where Actions or State are being used. 
I also added an extra note on the extra parenthesis with a link to the Typescript guide, but if people feel that's superfluous, I can revert that commit.
> Improve types in Immer middleware docs

- src/context.ts
- src/react.ts
- src/react/shallow.ts
- src/traditional.ts
Fixes https://github.com/pmndrs/zustand/issues/1395#issuecomment-1783619389
To avoid errors when Zustand is used on server as ESM.
> fix: importing CJS React in ESM

- package.json
Fixes #2163
The types for should be under each type of import. For instance "import", "module", "require" and "default"
> Update export types

- src/vanilla.ts
- tests/vanilla/basic.test.ts
unexpected behavior when update state with [`null`]
[current logic here](https://github.com/pmndrs/zustand/blob/main/src/vanilla.ts#L76C28-L76C28)
the code above will cause something like
```typescript
const useStore = create<string | null>(() => 'default');
useStore.setState(null); // will actually run: Object.assign({}, 'default', null)
useStore.getState(); // get { "0": "d", "1": "e", "2": "f", "3": "a", "4": "u", "5": "l",  "6": "t" }
```
> fix(vanilla): unexpected null state update behavior

- CONTRIBUTING.md
The contribution docs referenced an old command after the migration to `vitest` in #1753.
> docs(contributing): update test command

- rollup.config.js
- src/context.ts
- src/index.ts
- src/react.ts
- src/shallow.ts
- src/vanilla.ts
- tests/context.test.tsx
> [v5] breaking: drop default exports

- docs/integrations/immer-middleware.md
There are typing errors in the immer integration example.
> docs(immer): fix wrong typing

- tests/shallow.test.tsx
- tests/subscribe.test.tsx
- tests/vanilla/subscribe.test.tsx
Related to the discussions on this PR: 
- https://github.com/pmndrs/zustand/pull/2235/files#r1421258883
- https://github.com/pmndrs/zustand/pull/2235/files#r1421259086
Instead of testing the deprecated features, we should test the stable ones. Also, to have more detailed testing, we should test the subscription methods in zustand/vanilla.
Thank you
> chore(test): stop testing deprecated features and test subscribe in vanilla

- docs/guides/typescript.md
- docs/integrations/persisting-store-data.md
- related to https://github.com/pmndrs/zustand/pull/2235/files#r1421775346
This PR updates documentation that references features deprecated in v4.
> chore(docs): rewrite to remove deprecated references in persist docs

- docs/guides/flux-inspired-practice.md
Fixes a minor typo in the docs.
> docs: minor typo fix in flux-inspired-practice.md

- docs/integrations/third-party-libraries.md
Adding zustand dev tool made by oslabs to the third party libraries.
Fixes #
> Adding Zusty (zustand dev tool) to the third party libraries

- package.json
- rollup.config.js
> [v5]: drop "module" condition 

- package.json
> [v5] use "./*" in package.json exports and change Node.js requirement

- readme.md
- src/middleware/persist.ts
- src/react.ts
- src/traditional.ts
- src/vanilla.ts
- tests/basic.test.tsx
- tests/ssr.test.tsx
- tests/vanilla/basic.test.ts
This PR adds a new `getInitialState` method to the store api, which will always return the initial state that was used to create the store. The `persist` middleware also implements this method because it alters the initial state when restoring from a storage.
In React, this new method can then be used for `getServerSnaphot` in `useSyncExternalStore` to avoid avoid hydration mismatches when the state changes between the SSR and the first CSR. This could happen before when using the persist middleware, but can also happen whenever the store state was changed on the client only before completing the first CSR.
Fixes #1174
> feat: getInitialState

- src/react.ts
- src/traditional.ts
Related: https://github.com/pmndrs/zustand/discussions/1174#discussioncomment-7888322
`api.getServerState` is unused and undocumented. Let's deprecate it for removal in v5 _unless_ we want to provide this as an escape hatch for when server and client state need to differ, if that's the case, then I'll close this and add documentation. @dai-shi, @dbritto-dev, @sewera, thoughts on documentation or deprecation?
> fix: Add deprecation notice for getServerState() in WithReact type

- docs/integrations/persisting-store-data.md
Addresses https://github.com/pmndrs/zustand/discussions/2247#discussioncomment-7903804
Adds simple docs about `createJSONStorage` including `reviver` and `replacer`. Please let me know if anything should change. Thank you
> docs(persist): add info about `createJSONStorage` helpful function

- src/react.ts
- src/traditional.ts
For #2138
After some discussion, we will drop `getServerState` in v5 because it is inaccessible from the userland, and `getInitialState` solves the problem. 
Please let me know if any updates should be made. Thank you
> [v5]: Drop `getServerState`

- src/react.ts
for #2138
Just forgot it in https://github.com/pmndrs/zustand/pull/2237#issuecomment-1901773891
> [v5]: do not depend on use-sync-external-store

- src/react.ts
- src/react/shallow.ts
- tests/basic.test.tsx
for #2138 
the previous version has an issue with a corner case.
> [v5]: refactor useMemoSelector

- docs/guides/nextjs.md
Fixes #
On the nextjs guide, there is a link to ssr and hydration, but the link had a typo in it resulting in a 404 page
> fix broken link caused by typo

- docs/guides/nextjs.md
> Remove Partial type from init state on nextjs guide

- docs/guides/nextjs.md
Improve nextjs guide -> repo: https://github.com/dbritto-dev/zustand-next-demo
> Update nextjs guide

- src/middleware/persist.ts
Right now, we're requiring new `StateStorage` implementations to forcefully return `void` from inside `setItem` and `removeItem`.
When using a library that returns the set value for `setItem` or `removeItem`, therefore returning  a `string`, it causes Typescript to fail, requiring some weird workarounds.
For example, when using `localforage` (https://github.com/localForage/localForage) one needs to do what we describe below. Notice the `void` keyword.
```typescript
const storage: StateStorage = {
...localForage,
setItem: void localForage.setItem.bind(localForage)
}
```
Another, longer, alternative is
```typescript
const storage: StateStorage = {
...localForage,
// Curly braces are required because we need to "return `void`"
setItem: (name, value) => {
localStorage.setItem(name, value)
}
} …
```
> Relax types for `persist` middleware

- docs/guides/prevent-rerenders-with-use-shallow.md
> Fix typo in prevent-rerenders-with-use-shallow.md

- src/vanilla/shallow.ts
We have `Object.hasOwn` and it looks more readable and intuitive than `Object.prototype.hasOwnProperty.call`.
> refactor: Switch to Object.hasOwn

- package.json
Corepack chooses package manager to use with the field `packageManager`. For users using Yarn through Corepack, this is a real convenience.
> Enable usage of Corepack

- src/vanilla/shallow.ts
> refactor: Use for..of instead of C-style for

- src/middleware/persist.ts
Fixes #
Return type of migrate function  was not correct, should be PersisedState instead of S
> fix: return type of persist migrate function changed to PersistedState

- rollup.config.js
follow https://github.com/pmndrs/jotai/pull/2419
> build: target es2018

- src/react.ts
- tests/basic.test.tsx
- tests/ssr.test.tsx
For #2138 
I think useMemoSelector is a hack that should be avoided. We should generally follow how React works. If we need previous behavior, we should use `zustand/traditional` which is based on a library provided by React, instead of adding our own hack.
> [v5]: follow React "standard" way with breaking behavioral change

- src/vanilla/shallow.ts
- tests/vanilla/shallow.test.tsx
for #2138 
done > https://github.com/pmndrs/zustand/discussions/2392#discussioncomment-8681622
> [v5] Rewrite shallow to support iterables

- rollup.config.js
For #2138 
There was an issue in #2380.
> [v5] fix rollup config for cjs

- readme.md
- src/middleware/devtools.ts
- tests/devtools.test.tsx
For #2138
Fixes #2404
Related #2405 
Using the devtools middleware will warn in all non-browser environments during development. This was added many years ago and likely can be removed. The docs are updated to link to the Redux DevTools Chrome extension.
> [v5] Remove Devtools warning

- docs/integrations/third-party-libraries.md
https://twitter.com/dai_shi/status/1785451672934003147
Adding my third party library to the list ◡̈
> docs: add zustand-context to third party libs

- docs/guides/nextjs.md
There are two typos in the error message argument. `useCounterStore must be use` => `useCounterStore must be used`
Fixes #
Same as above
> Fix typos in nextjs.md

- docs/guides/typescript.md
Change in the description of the order of middleware.
> Update typescript.md - middleware order

- docs/integrations/third-party-libraries.md
https://www.npmjs.com/package/zustand-computed-state
> doc: added zustand-computed-state to external libraries

- src/react.ts
- src/traditional.ts
Fixes https://github.com/pmndrs/zustand/discussions/2581
`UseBoundStore` types were relaxed in https://github.com/pmndrs/zustand/pull/1589 because the internals of this method did not use any of the setters, only getters. We can also do this for `useStore` types because its API only uses getters.
Context: I am building a library that returns a store API with only getter methods exposed and I would like folks to be able to pass this directly into Zustand's `useStore` React helper.
> useStore uses ReadonlyStoreApi

- package.json
Fixes #2621
Adding `"type": "commonjs"` seemed safe, but zustand v4 still has unofficial `"module"` condition which seems invalid. Let's revert it in v4 only.
> fix: no type field in package.json

- docs/integrations/third-party-libraries.md
Created a third party package that is built on top of zustand and provides interval based saving to store
> doc:  Added zustand-interval-persist to third party

- readme.md
Fixes #
targeted section of the README talks about integration with redux devtools. to accomplish this the dev needs to define third argument for `set` function. since arguments for `set` function are positional it means he/she needs to define the second, `replace`, argument as well
currently README suggests just to use `false` value for `replace` arg i.e. to override the default value by identical manual one, but defined on the dev side.
more clean way would be to use `undefined` at the second argument position that will make JS itself to use the default value, meaning moving control of it back lib authors, not dev
> (docs) remove unintended change from default merge behaviour to identical but manual one

- docs/integrations/persisting-store-data.md
I spent way too much time on figuring out why my state was empty.
I hope this change will save that time for other devs.
Calling `setHasHydrated` directly in `onRehydrateStorage` causes the state to only contain the `{ _hasHydrated: true }` rather than the actual hydrated state (which I believe is then lost).
`setHasHydrated` must instead be called from the function returned from  `onRehydrateStorage`, as that function will be called after the state has been hydrated.
Fixes #
> Fix store-persistence example

- examples/demo/index.html
I fixed the `og:iamge`
attribute name to `content` according to the [Open Graph Protocol spec](https://ogp.me/#metadata). 
Thanks for always actively maintaining such a great library!
> fix: "value" to "content" attr for og:image

- src/middleware/persist.ts
- tests/persistSync.test.tsx
Fixes https://github.com/pmndrs/zustand/discussions/2663
This PR avoids a `setItem` call with the state just reteived from the storage.
> fix(storage): avoid calling setItem with the state just retrieved

- docs/integrations/persisting-store-data.md
--HG--
branch : discussion-2689-persist-doc-map-and-set-missing-version
Fixes # Discussion 2689
Fixes getItem and setItem on the storage for the Map & Set persist example, so that respectfully those methods retrieves and sets the version when present.
- [v] `pnpm run prettier` for formatting code and docs
> Persist documentation for Map & Set add storage and retrieval of version

- src/middleware/immer.ts
- tests/middlewareTypes.test.tsx
Bases the type of `setState` off of `setState` instead of `getState`.
Fixes #1621
This PR fixes the Immer middleware so that the type of `setState` is inferred off of the store's `setState` as opposed to `getState`. When using a middleware like [zustand-computed](https://github.com/chrisvander/zustand-computed), this would previously have the result of a differing `getState` generic would move over to `setState` unintentionally.
> Fix Immer type inference for `setState`

- docs/guides/typescript.md
Hello, I noticed a typo in typescript docs in the section "Bounded `useStore` hook for vanilla stores". In the second example, `createBoundedUseStore` is not passing `selector` to `useStore`.
> rdocs: typo in typescript docs

- readme.md
Corrected store shape in "Selecting multiple state slices" to be consistent with the example (which use `nuts`, `honey`, and `treats` instead of `bears`).
> docs: corrected example

- docs/integrations/third-party-libraries.md
Hello, I read [contributing guide](https://github.com/pmndrs/zustand/blob/main/CONTRIBUTING.md). However, the docs branch of `website` is missing and I can't find proper way.
So I created a PR in a simple way, and if this causes problems or results in the documentation not being properly updated, I would like to know what actions I should take.
Add `zustand-async-slice` package into zustand third party library listing.
> [Zustand Docs] Add third party library `zustand-async-slice`

- src/react.ts
- src/react/shallow.ts
- src/traditional.ts
I was rushing too much.
#2701 was to avoid react compiler warning, but it seems like the warning was caused because of destructuring `ReactExports`. The eslint rules aren't capable of it. Instead, let's use traditional `React.useRef`. This reverts #2701.
> revert useShallow refactor in #2701

- docs/migrations/migrating-to-v5.md
N/A
Hi everyone, I noticed that the error message code block in the [v5 migration guideline](https://zustand.docs.pmnd.rs/migrations/migrating-to-v5#requiring-stable-selector-outputs)  doesn’t display correctly on the docs site, so I added the `plaintext` language to the code block to prevent layout breaks. 
Feel free to close this if it is unnecessary.
**Before**
**After**
> docs: add plaintext language to code block to prevent layout breaks

- docs/migrations/migrating-to-v5.md
https://github.com/pmndrs/zustand/issues/2741#issuecomment-2359569305
> fix(docs): improve v5 migration guide

- docs/guides/prevent-rerenders-with-use-shallow.md
Fix type in Prevent rerenders with useShallow section
> docs: fix typo in Prevent rerenders with useShallow section

- docs/guides/typescript.md
Fix typo in "TypeScript Guide" section.
> docs: Fix typo in "TypeScript Guide" section

- docs/guides/typescript.md
NA
- Updates the two TypeScript middleware authoring examples to remove references to `State` which was removed in zustand v5: https://github.com/charkour-labs/zustand/commit/0cb47c8dde015cd4e42fe48f2b4b67472174903b#diff-b68a2cbc8606fe37f9c2c72867a87ff50a11c2b38a6d9de45a94281f02bf0a4eL125
- Improve type casting; replace `as any` with `as Parameters<setState>`. The typings were updated here: https://github.com/pmndrs/zustand/pull/2580
> docs: remove State and improve `replace` typecasting

- docs/apis/create-store.md
- docs/apis/create-with-equality-fn.md
- docs/apis/create.md
- docs/apis/shallow.md
- docs/guides/auto-generating-selectors.md
- docs/guides/connect-to-state-with-url-hash.md
- docs/guides/event-handler-in-pre-react-18.md
- docs/guides/flux-inspired-practice.md
- docs/guides/how-to-reset-state.md
- docs/guides/immutable-state-and-merging.md
- docs/guides/initialize-state-with-props.md
- docs/guides/maps-and-sets-usage.md
- docs/guides/nextjs.md
- docs/guides/practice-with-no-store-actions.md
- docs/guides/prevent-rerenders-with-use-shallow.md
- docs/guides/slices-pattern.md
- docs/guides/ssr-and-hydration.md
- docs/guides/testing.md
- docs/guides/typescript.md
- docs/guides/updating-state.md
- docs/hooks/use-shallow.md
- docs/hooks/use-store-with-equality-fn.md
- docs/hooks/use-store.md
- docs/integrations/immer-middleware.md
- docs/integrations/persisting-store-data.md
- docs/integrations/third-party-libraries.md
- docs/migrations/migrating-to-v4.md
- docs/migrations/migrating-to-v5.md
- docs/previous-versions/zustand-v3-create-context.md
The "next" link at the bottom of  https://zustand.docs.pmnd.rs/guides/prevent-rerenders-with-use-shallow points to https://zustand.docs.pmnd.rs/integrations/immer-middleware when it should be pointing to https://zustand.docs.pmnd.rs/guides/ssr-and-hydration instead (i.e. the next page in the list of links in the sidebar).
This PR updates all the `nav` numbers in order to correct the navigation order. If this is not the right solution, please feel free to edit this PR with a better one.
> Fix "previous" and "next" navigation links

- docs/getting-started/introduction.md
The JPG image has been replaced with an AVIF version, which offers better compression and faster loading times, AVIF (which is supported by 92.64% of browsers worldwide according to [caniuse](https://caniuse.com/avif)). This optimizes page performance without compromising compatibility or image quality.
> docs: logo optimization and adding alt

- docs/hooks/use-store.md
there is a typo mistake while importing the setposition from positionstore
wrong : const setPosition = useStore(positionStore, (state) => state.setPositionStore)
correct :  const setPosition = useStore(positionStore, (state) => state.setPosition)
Fixes #
spelling mistake  of this line 
```
const setPosition = useStore(positionStore, (state) => state.setPosition)
```
> fix(typo):  fix import of setPosition 

- src/vanilla/shallow.ts
- tests/vanilla/shallow.test.tsx
Fixes #2794 
There is a logic to guess map-like iterator but it's not perfect. This adds fallback.
> fix(shallow): fallback map-like iterator comparison

- docs/integrations/third-party-libraries.md
Add leo-query to third party libs.
> docs: add leo-query to third-party libraries list

- src/vanilla/shallow.ts
- tests/vanilla/shallow.test.tsx
Using the same tests in #2816.
> fix(shallow): iterable-like insensitive keys order comparison (alternate implementation)

- tests/basic.test.tsx
- tests/persistAsync.test.tsx
Tests using React Testing Library should use `screen` instead of queries methods returned by `render`.
- [ x] `pnpm run prettier` for formatting code and docs
> test: use screen exposed by React Testing Library

- docs/guides/how-to-reset-state.md
- docs/guides/testing.md
- docs/guides/tutorial-tic-tac-toe.md
> chore(docs): update docs content

- docs/guides/tutorial-tic-tac-toe.md
> fix(doc): update tutorial guide and fix doc build

- docs/guides/tutorial-tic-tac-toe.md
There is a  mistake in the store name
Fixes #
It's should be `useGameStore`  as seen in the code block above
wrong : `useSquaresStore` declares a `squares` state that's initially set to that array. Each entry in the
correct : `useGameStore` declares a `squares` state that's initially set to that array. Each entry in the
> docs: fix typo in tutorial-tic-tac-toe.md

- docs/migrations/migrating-to-v5.md
NA
Update the v5 Migration docs to match the TypeScript documentation: https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md#handling-dynamic-replace-flag. This ensures consistency in both places.
> chore: match the typescript docs

- docs/migrations/migrating-to-v5.md
I've replaced `middlware` with `middleware` in md file.
> Fix migrating to v5 doc

- src/middleware/devtools.ts
- src/vanilla.ts
- tests/middlewareTypes.test.tsx
Fixes #2700
- Added inferred generic type variables `U` with some of them extending from the generic `T`, to support inferred return type
- Added corresponding tests using the cases in #2700
Seems like no documentation update would be needed for this PR. Please feel free to let me know if I should update the docs.
> fix(middleware): devtools type error #2700

- docs/middlewares/devtools.md
Came to this page to double check where I import `devtools` from, noticed it missing from the code sample
> chore(docs): Adds import statements to devtools code example

- CONTRIBUTING.md
* The correct command is not `pnpm` but `pnpm install`
> docs(CONTRIBUTING.md): change 'pnpm' to 'pnpm install' for installing dependencies

- eslint.config.mjs
* Change `dist` area in `ignores`.
* We can just ignore the `./dist`.
* Sort `rules` by the order `plugins` were added and by name.
* It is to make it more predictable for the user and improve readability.
> chore(eslint): change 'dist' area in 'ignores', sort rules

- .github/workflows/compressed-size-action.yml
- .github/workflows/cr.yml
- .github/workflows/lint-and-type.yml
- .github/workflows/publish.yml
- .github/workflows/test-multiple-builds.yml
- .github/workflows/test-multiple-versions.yml
- .github/workflows/test-old-typescript.yml
* Change `node-version` to `lts/*` to always use the latest LTS version of Node.js.
> chore(.github/workflows): change 'node-version' to 'lts/*' in 'actions/setup-node'

- docs/apis/create.md
Fixes #
Fixed incorrect state selector syntax in the troubleshooting example of create.md. The original code had a circular reference issue where person and setPerson were trying to reference themselves. Updated the selectors to correctly access the state and setPerson from the store state.
> docs(create.md): fix state selector syntax in troubleshooting example

- rollup.config.js
I think I forgot this change when Zustand v5 lands.
<details>
<summary>git diff --no-index dist.orig dist</summary>
```diff
diff --git a/dist.orig/esm/index.d.mts b/dist/esm/index.d.mts
index a65c352..a1afbf8 100644
--- a/dist.orig/esm/index.d.mts
+++ b/dist/esm/index.d.mts
@@ -1,2 +1,2 @@
-export * from './vanilla.mjs';
-export * from './react.mjs';
+export * from 'zustand/vanilla';
+export * from 'zustand/react';
diff --git a/dist.orig/esm/middleware/combine.d.mts b/dist/esm/middleware/combine.d.mts
index d6ebb81..929f8a6 100644
--- a/dist.orig/esm/middleware/combine.d.mts
+++ b/dist/esm/middleware/combine.d.mts
@@ -1,4 +1,4 @@
-import type { StateCreator, StoreMutatorIdentifier } from '../vanilla.mjs';
+import type { StateCreator, StoreMutatorIdentifier } from 'zustand/vanilla';
type …
```
> fix(build): alias entries in rollup config

- docs/apis/create-with-equality-fn.md
- docs/apis/shallow.md
Fixes #
* Fixed incorrect state update pattern in Form example where setPerson was using `person` instead of `{ person: nextPerson }`
* Fixed TypeScript type definition typos in form handlers, correcting `HTLMInputElement` to `HTMLInputElement` in three event handler functions
Fixed variable name typos in BigInt comparison example `bigInLeft, bigInRight` to `bigIntLeft, bigIntRight`
> docs(create-with-equality-fn.md): fix typos in event handler type definitions

- rollup.config.mjs
* Clarify variables in `rollup.config.mjs`
> chore(rollup): clarify the callback argument 'e' to 'entry'

- docs/integrations/third-party-libraries.md
We've renamed the package from `@udecode/zustood` to `zustand-x` a while back.
> Rename zustood to zustand-x

- README.md
Fixes #
Redux devtools example has and additional comma which is incorrect. Removed that
> docs(README.MD): fix redux middleware example

- .github/workflows/cr.yml
- .github/workflows/lint-and-type.yml
- .github/workflows/publish.yml
- .github/workflows/test-multiple-builds.yml
- .github/workflows/test-multiple-versions.yml
- .github/workflows/test-old-typescript.yml
- package.json
- We agreed to avoid using aliases.
- Replaced `pnpm <command>` with `pnpm run <command>` for all related commands.
- Explicitly added `run` to avoid potential conflicts with pnpm's lifecycle commands, as omitting `run` can cause conflicts.
- This change was made to maintain consistency with existing commands that already use the `pnpm run <command>` format.
- Adding `run` ensures that commands are clearly separated from pnpm's lifecycle commands, preventing conflicts.
- Using `pnpm run` helps clarify the intention of running a script.
- This change aligns with the existing usage of `pnpm run`, maintaining consistency across the codebase.
> chore(*): replace 'pnpm <command>' with 'pnpm run <command>'

- docs/integrations/third-party-libraries.md
Fixes # N/A
Add [zustand-multi-persist](https://github.com/mooalot/zustand-multi-persist) to 3rd party integrations. It's a package that wraps zustand/persist to allow for multiple storages.
> docs: added zustand-multi-persist to 3rd party

- package.json
- pnpm-lock.yaml
* Upgraded pnpm from v8 to the stable v9
* Compatibility concerns with various libraries
* pnpm 10 was recently released, and its stability has not been fully verified yet
* For now, we are applying the stable pnpm 9, and we will consider upgrading to pnpm 10 once its stability is confirmed
> chore(package.json): upgrade pnpm from v8 to v9

- vitest.config.mts
Vitest 3 suggest to migrate from 'basic' reporter to 'default'
```
DEPRECATED  'basic' reporter is deprecated and will be removed in Vitest v3.
Remove 'basic' from 'reporters' option. To match 'basic' reporter 100%, use configuration:
{
"test": {
"reporters": [
[
"default",
{
"summary": false
}
]
]
}
}
```
Secondly, `provider` in `coverage` is required and produces TypeScript error when not defined explicitly.
> chore: use github test reporter on CI and fix TS error

- docs/guides/testing.md
in vite,
mergeConfig accepts only config in object form. If you have a config in callback form, you should call it before passing into mergeConfig.
You can use the defineConfig helper to merge a config in callback form with another config:
https://vite.dev/guide/api-javascript.html#mergeconfig
Fixes #
> docs: update vitest config to match vitest docs

- docs/hooks/use-shallow.md
- docs/middlewares/immer.md
> docs: Fix typos in code examples in the document

- docs/integrations/third-party-libraries.md
Zutron is now deprecated, I have replaced it with `zubridge` which also supports tauri via `@zubridge/tauri` and `@zubridge/tauri-v1`.
`@zubridge/electron` is a direct replacement for `zutron`:
`zutron` => `@zubridge/electron`
> docs: remove zutron, add zubridge

- docs/guides/nextjs.md
Resolves #3052 by explicitly making the type argument to `useRef` nullable.
> Update Next.js guide to have explicitly nullable `useRef` type argument

- examples/demo/src/components/Scene.jsx
This PR improves the demo site's error handling when hardware acceleration is disabled in the browser. The changes include: as discussed in #3071 
- Added a fallback UI
The fallback scene now shows:
- A static image of the Zustand ogimage
This fixes the issue where the demo site would break without any feedback when hardware acceleration is disabled.
Testing:
- fallback works when hardware acceleration is disabled
Fixes #
> fix: handle hardware acceleration disabled scenario in demo site

- README.md
I think it was a mistake to define 2 variables in an example with the same name
Fixes #
> Fix small issue in README.md

- eslint.config.mjs
- src/traditional.ts
- vitest.config.mts
> chore(eslint): enforce file extension usage for internal modules, ignore external packages

- tests/vanilla/shallow.test.tsx
> test(vanilla/shallow): add test for pure iterable with different values returns false

- tests/vanilla/subscribe.test.tsx
> test(vanilla/subscribe): add test for covering fireImmediately option in 'subscribeWithSelector'

- src/middleware.ts
Fixes #
* Aligned export format with [`middleware.ts`](https://github.com/pmndrs/zustand/blob/main/src/middleware.ts)
* Even if we use export `*` syntax, we still only export `useShallow` in [`react/shallow.ts`](https://github.com/pmndrs/zustand/blob/main/src/react/shallow.ts) and `shallow` in [`vanilla/shallow.ts`](https://github.com/pmndrs/zustand/blob/main/src/vanilla/shallow.ts)
> refactor(middleware): replace export * with explicit named and type exports

- examples/demo/src/components/Scene.jsx
- tests/types.test.tsx
remove unused import in example & fix typo in tests
> refactor: remove unused import in example & fix typo in tests

- docs/guides/auto-generating-selectors.md
I hope this is a correct change, but I was reading the docs, and if I didn't misunderstand, we always need to do currying when creating a store with typescript. This seemed to be missing in the code example used in auto generating selectors.
> docs: add currying for createStore

- src/middleware/persist.ts
- tests/persistAsync.test.tsx
fix #3196 
persist middleware to mutate `setState` so that it returns what storage.setItem returns.
This is a suboptimal solution as we can't infer types. It's always `unknown`. Nevertheless, it should be usable if we assert types in a certain case.
> feat(middleare/persist): return storage promise from setState

- package.json
same with https://github.com/pmndrs/jotai/pull/3138
Upgrade pnpm from v9.15.5 to v10.15.0 to stay up-to-date with latest stable version.
> chore: upgrade pnpm to v10.15.0
